"""Phase 3 remainder: hand-translated RU backfill for GameQuestion quiz rows
in sessions 58 (Python fundamentals), 59 (JavaScript), 61 (HTML/CSS advanced
+ portfolio projects). No translation API used — every string below composed
by hand.

Idempotent: only updates rows still missing question_text_ru or options_ru;
safe to re-run. ORM-only via AsyncSessionLocal, no DDL, no app.main import.
"""
from __future__ import annotations

import asyncio
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # noqa: E402

from sqlalchemy import select, or_  # noqa: E402
from app.db.database import AsyncSessionLocal  # noqa: E402
from app.db import base as _base  # noqa: E402,F401
from app.models.team_game import GameQuestion  # noqa: E402

SESSIONS = [58, 59, 61]

# ─────────────────────────────────────────────────────────────────────────
# QUESTION_MAP: question_text (uz) -> question_text_ru
# ─────────────────────────────────────────────────────────────────────────
QUESTION_MAP: dict[str, str] = {
    # ---- session 58: Python fundamentals ----
    "Python'ni kim yaratdi?": "Кто создал Python?",
    "Python faylining kengaytmasi?": "Какое расширение у файла Python?",
    "Python'da kommentariy qanday?": "Как пишется комментарий в Python?",
    "Python'da print() nima?": "Что делает print() в Python?",
    "Python'da indentatsiya nima uchun?": "Для чего нужны отступы в Python?",
    "Python interpreterlash nima?": "Что такое интерпретация в Python?",
    "Python 2 va 3 farqi?": "В чём разница между Python 2 и 3?",
    "Python'da range(5) nima?": "Что такое range(5) в Python?",
    "Python'da int nima?": "Что такое int в Python?",
    "float nima?": "Что такое float?",
    "str('42') nima?": "Что такое str('42')?",
    "Python'da None nima?": "Что такое None в Python?",
    "x = 10; x += 3 natijai?": "Чему равен результат x = 10; x += 3?",
    "Python'da type(3.14) nima qaytaradi?": "Что возвращает type(3.14) в Python?",
    "Python'da bool turi nima qaytaradi?": "Что возвращает тип bool в Python?",
    "Python'da konvertatsiya: int('10') nima?": "Что такое преобразование int('10') в Python?",
    "Python'da satr yaratish?": "Как создать строку в Python?",
    "Satr uzunligi qanday topiladi?": "Как найти длину строки?",
    "Satr kesish (slicing)?": "Срез строки (slicing)?",
    "Satr metodlaridan biri?": "Один из методов строк?",
    "f-string nima?": "Что такое f-строка?",
    "'hello'.replace('l','r') nima?": "Чему равно 'hello'.replace('l','r')?",
    "'python'.find('th') nima?": "Чему равно 'python'.find('th')?",
    "'a,b,c'.split(',') nima?": "Чему равно 'a,b,c'.split(',')?",
    "Kalkulyator uchun qaysi Python operatorlari kerak?": "Какие операторы Python нужны для калькулятора?",
    "Python'da foydalanuvchidan kiritish olish?": "Как получить ввод от пользователя в Python?",
    "Python'da int() nima?": "Что делает int() в Python?",
    "// operatori nima?": "Что такое оператор //?",
    "% operatori nima?": "Что такое оператор %?",
    "** operatori nima?": "Что такое оператор **?",
    "ZeroDivisionError nima?": "Что такое ZeroDivisionError?",
    "round(3.7) nima?": "Чему равно round(3.7)?",
    "if-elif-else qanday tartibda?": "В каком порядке идут if-elif-else?",
    "Compound shart nima?": "Что такое составное условие?",
    "'x > 0 and x < 10' ekvivalenti?": "Что эквивалентно 'x > 0 and x < 10'?",
    "not True nima?": "Чему равно not True?",
    "Python'da in operatori?": "Что такое оператор in в Python?",
    "Ternary (bir qatorli if) Python'da?": "Тернарный (однострочный if) в Python?",
    "Nol qiymat shartlarda qanday baholanadi?": "Как ноль оценивается в условиях?",
    "else bloki if bilan qachon bajariladi?": "Когда выполняется блок else при if?",
    "for sikli Python'da?": "Цикл for в Python?",
    "while sikli nima?": "Что такое цикл while?",
    "enumerate() nima?": "Что такое enumerate()?",
    "zip() nima?": "Что такое zip()?",
    "continue nima?": "Что делает continue?",
    "break nima?": "Что делает break?",
    "else with for nima?": "Что такое else при for?",
    "Nested loop nima?": "Что такое вложенный цикл?",
    "Python ro'yxat (list) nima?": "Что такое список (list) в Python?",
    "Tuple nima?": "Что такое кортеж (tuple)?",
    "List vs Tuple farqi?": "В чём разница между list и tuple?",
    "list.append() va list.extend() farqi?": "В чём разница между list.append() и list.extend()?",
    "list.sort() va sorted() farqi?": "В чём разница между list.sort() и sorted()?",
    "Tuple unpacking nima?": "Что такое распаковка кортежа?",
    "list[::-1] nima?": "Что такое list[::-1]?",
    "list.pop(0) nima?": "Что делает list.pop(0)?",
    "To'plam uchun qaysi Python struktura?": "Какая структура Python используется для множества?",
    "set'da noyob elementlar nima?": "Что означают уникальные элементы в set?",
    "set.add() nima?": "Что делает set.add()?",
    "set intersection nima?": "Что такое пересечение множеств (intersection)?",
    "Shopping list CRUD uchun list yaxshimi?": "Подходит ли list для CRUD списка покупок?",
    "list comprehension nima?": "Что такое list comprehension?",
    "sorted() funksiyasi reverse=True bilan?": "Функция sorted() с reverse=True?",
    "list nima uchun set'dan sekinroq qidiruvda?": "Почему list медленнее set при поиске?",
    "Python funksiya e'lon qilish?": "Как объявить функцию в Python?",
    "Funksiya argumentlari nima?": "Что такое аргументы функции?",
    "*args nima?": "Что такое *args?",
    "**kwargs nima?": "Что такое **kwargs?",
    "Lambda funksiya nima?": "Что такое лямбда-функция?",
    "Scope nima?": "Что такое область видимости (scope)?",
    "global kalit so'zi nima?": "Что такое ключевое слово global?",
    "Rekursiya nima?": "Что такое рекурсия?",
    "Faylni ochish uchun?": "Как открыть файл?",
    "with open() nima?": "Что такое with open()?",
    "try-except nima?": "Что такое try-except?",
    "except Exception as e nima?": "Что такое except Exception as e?",
    "finally bloki nima?": "Что такое блок finally?",
    "raise nima?": "Что делает raise?",
    "FileNotFoundError nima?": "Что такое FileNotFoundError?",
    "Custom exception nima?": "Что такое пользовательское исключение (custom exception)?",
    "Python sinf (class) nima?": "Что такое класс (class) в Python?",
    "__init__ nima?": "Что такое __init__?",
    "self nima?": "Что такое self?",
    "Meros (inheritance) nima?": "Что такое наследование (inheritance)?",
    "super() nima?": "Что такое super()?",
    "Polimorfizm nima?": "Что такое полиморфизм?",
    "@classmethod nima?": "Что такое @classmethod?",
    "@staticmethod nima?": "Что такое @staticmethod?",
    "Lug'at ilovasi uchun qaysi Python tuzilma?": "Какая структура Python используется для приложения-словаря?",
    "Kalit-qiymat qidirish tezligi?": "Какова скорость поиска по ключу-значению?",
    "So'zlikda tarjima qo'shish?": "Как добавить перевод в словарь?",
    "JSON va dict farqi?": "В чём разница между JSON и dict?",
    "defaultdict nima?": "Что такое defaultdict?",
    "So'zlikni faylga saqlash?": "Как сохранить словарь в файл?",
    "Counter({'a':3,'b':1}).most_common(1) nima?": "Чему равно Counter({'a':3,'b':1}).most_common(1)?",
    "Lug'atdan kalitni xavfsiz o'chirish?": "Как безопасно удалить ключ из словаря?",
    "Python moduli nima?": "Что такое модуль Python?",
    "import nima?": "Что делает import?",
    "from module import func nima?": "Что такое from module import func?",
    "Python paketi nima?": "Что такое пакет Python?",
    "PyPI nima?": "Что такое PyPI?",
    "pip nima?": "Что такое pip?",
    "Standard kutubxonadan biri?": "Один из модулей стандартной библиотеки?",
    "Virtual muhit (venv) nima uchun?": "Для чего нужна виртуальная среда (venv)?",
    "Python lug'at (dict) nima?": "Что такое словарь (dict) в Python?",
    "dict[key] va dict.get(key) farqi?": "В чём разница между dict[key] и dict.get(key)?",
    "dict.items() nima?": "Что такое dict.items()?",
    "set nima?": "Что такое set?",
    "dict.pop(key) nima?": "Что делает dict.pop(key)?",
    "frozenset nima?": "Что такое frozenset?",
    "dict.update() nima?": "Что делает dict.update()?",
    "Counter nima?": "Что такое Counter?",

    # ---- session 59: JavaScript ----
    "Array.prototype.at() nima?": "Что такое Array.prototype.at()?",
    "structuredClone() nima?": "Что такое structuredClone()?",
    "Object.hasOwn() nima?": "Что такое Object.hasOwn()?",
    "globalThis nima?": "Что такое globalThis?",
    "Promise.allSettled() nima?": "Что такое Promise.allSettled()?",
    "Array'ning find va at farqi?": "В чём разница между find и at у массива?",
    "Logical assignment (&&=, ||=, ??=) nima?": "Что такое логическое присваивание (&&=, ||=, ??=)?",
    "Array.prototype.toSorted() nima?": "Что такое Array.prototype.toSorted()?",
    "Array.find() va filter() farqi?": "В чём разница между Array.find() и filter()?",
    "flat() nima?": "Что такое flat()?",
    "findIndex() nima?": "Что такое findIndex()?",
    "every() nima?": "Что такое every()?",
    "some() nima?": "Что такое some()?",
    "Array.from({length:5}, (_,i)=>i) nima?": "Чему равно Array.from({length:5}, (_,i)=>i)?",
    "flatMap() nima?": "Что такое flatMap()?",
    "Array spread [...a,...b] nima?": "Что такое спред массива [...a,...b]?",
    "localStorage nima?": "Что такое localStorage?",
    "localStorage.setItem() nima?": "Что делает localStorage.setItem()?",
    "localStorage.getItem() nima?": "Что делает localStorage.getItem()?",
    "localStorage va sessionStorage farqi?": "В чём разница между localStorage и sessionStorage?",
    "localStorage faqat satrmi?": "localStorage хранит только строки?",
    "localStorage.removeItem() nima?": "Что делает localStorage.removeItem()?",
    "localStorage.clear() nima?": "Что делает localStorage.clear()?",
    "localStorage hajm chegarasi?": "Каков лимит размера localStorage?",
    "Ob'ekt spread {...a,...b} nima?": "Что такое спред объекта {...a,...b}?",
    "Array destructuring nima?": "Что такое деструктуризация массива?",
    "Object.entries() nima?": "Что такое Object.entries()?",
    "Map va ob'ekt farqi?": "В чём разница между Map и объектом?",
    "Set nima?": "Что такое Set?",
    "Set.has() nima?": "Что делает Set.has()?",
    "WeakMap va Map farqi?": "В чём разница между WeakMap и Map?",
    "Symbol nima?": "Что такое Symbol?",
    "template literal nima?": "Что такое template literal (шаблонная строка)?",
    "forEach() nima?": "Что такое forEach()?",
    "Array.from() nima?": "Что такое Array.from()?",
    "element.children nima?": "Что такое element.children?",
    "event bubbling nima?": "Что такое всплытие событий (event bubbling)?",
    "event delegation nima?": "Что такое делегирование событий?",
    "NodeList vs Array farqi?": "В чём разница между NodeList и Array?",
    "MutationObserver nima?": "Что такое MutationObserver?",
    "appendChild() nima?": "Что делает appendChild()?",
    "removeChild() nima?": "Что делает removeChild()?",
    "insertBefore() nima?": "Что делает insertBefore()?",
    "element.style.color nima?": "Что такое element.style.color?",
    "dataset nima?": "Что такое dataset?",
    "cloneNode(true) nima?": "Что делает cloneNode(true)?",
    "innerHTML = '' nima qiladi?": "Что делает innerHTML = ''?",
    "element.getAttribute() nima?": "Что делает element.getAttribute()?",
    "DOM nima?": "Что такое DOM?",
    "document.getElementById() nima?": "Что делает document.getElementById()?",
    "innerHTML va textContent farqi?": "В чём разница между innerHTML и textContent?",
    "classList.add() nima?": "Что делает classList.add()?",
    "addEventListener('click', fn) nima?": "Что делает addEventListener('click', fn)?",
    "event.preventDefault() nima?": "Что делает event.preventDefault()?",
    "querySelector() va querySelectorAll() farqi?": "В чём разница между querySelector() и querySelectorAll()?",
    "document.createElement() nima?": "Что делает document.createElement()?",
    "JavaScript ob'ekti nima?": "Что такое объект JavaScript?",
    "Ob'ekt maydoniga kirish?": "Как получить доступ к полю объекта?",
    "Ob'ektga yangi maydon qo'shish?": "Как добавить новое поле в объект?",
    "Object.keys() nima?": "Что такое Object.keys()?",
    "Spread operator (...) ob'ektda nima qiladi?": "Что делает оператор расширения (...) с объектом?",
    "Destructuring nima?": "Что такое деструктуризация?",
    "JSON.stringify() nima?": "Что делает JSON.stringify()?",
    "JSON.parse() nima?": "Что делает JSON.parse()?",
    "Funksiya e'lon qilish?": "Как объявить функцию?",
    "Arrow funksiya sintaksisi?": "Синтаксис стрелочной функции?",
    "Funksiya parametri va argumenti farqi?": "В чём разница между параметром и аргументом функции?",
    "return nima qiladi?": "Что делает return?",
    "Default parametr nima?": "Что такое параметр по умолчанию?",
    "Rest parameter (...args) nima?": "Что такое rest-параметр (...args)?",
    "Funksiyaning hoist qilinishi nima?": "Что такое всплытие (hoisting) функции?",
    "Callback funksiya nima?": "Что такое функция обратного вызова (callback)?",
    "Array.push() nima?": "Что делает Array.push()?",
    "Array.map() nima?": "Что делает Array.map()?",
    "Array.filter() nima?": "Что делает Array.filter()?",
    "Array.find() nima?": "Что делает Array.find()?",
    "Array.includes() nima?": "Что делает Array.includes()?",
    "Array.slice() va splice() farqi?": "В чём разница между Array.slice() и splice()?",
    "Array.sort() nima?": "Что делает Array.sort()?",
    "Array.reduce() nima?": "Что делает Array.reduce()?",
    "for sikli to'g'ri sintaksisi?": "Правильный синтаксис цикла for?",
    "while sikli qachon to'xtaydi?": "Когда останавливается цикл while?",
    "do-while va while farqi?": "В чём разница между do-while и while?",
    "break sikl ichida nima?": "Что делает break внутри цикла?",
    "continue nima qiladi?": "Что делает continue?",
    "for...in nima uchun?": "Для чего нужен for...in?",
    "Cheksiz sikldan qochish uchun?": "Как избежать бесконечного цикла?",
    "Array'ning uzunligini olish?": "Как получить длину массива?",
    "Array'ga element qo'shish (oxiriga)?": "Как добавить элемент в массив (в конец)?",
    "Array'dan oxirgi elementni olib tashlash?": "Как удалить последний элемент из массива?",
    "for...of sikli nima?": "Что такое цикл for...of?",
    "Array'ning birinchi elementi indeksi?": "Каков индекс первого элемента массива?",
    "typeof [] nima qaytaradi?": "Что возвращает typeof []?",
    "Array.isArray([]) nima?": "Чему равно Array.isArray([])?",
    "arr.indexOf(val) nima?": "Что делает arr.indexOf(val)?",
    "&& operatori nima?": "Что такое оператор &&?",
    "|| operatori nima?": "Что такое оператор ||?",
    "! operatori nima?": "Что такое оператор !?",
    "switch-case'da 'fall-through' nima?": "Что такое 'сквозное выполнение' (fall-through) в switch-case?",
    "Qaysi qiymat falsy?": "Какое значение ложно (falsy)?",
    "Qaysi qiymat truthy?": "Какое значение истинно (truthy)?",
    "Nullish coalescing (??) nima?": "Что такое оператор нулевого слияния (??)?",
    "Optional chaining (?.) nima?": "Что такое опциональная цепочка (?.)?",
    "if-else nima uchun?": "Для чего нужен if-else?",
    "else if nima?": "Что такое else if?",
    "Ternary operator nima?": "Что такое тернарный оператор?",
    "switch-case nima?": "Что такое switch-case?",
    "break switch ichida nima qiladi?": "Что делает break внутри switch?",
    "default in switch nima?": "Что такое default в switch?",
    "JavaScript'da truthy/falsy nima?": "Что такое truthy/falsy в JavaScript?",
    "Short-circuit evaluation nima?": "Что такое сокращённое вычисление (short-circuit evaluation)?",
    "JavaScript nima?": "Что такое JavaScript?",
    "JavaScript'da o'zgaruvchi e'lon qilish?": "Как объявить переменную в JavaScript?",
    "console.log() nima?": "Что делает console.log()?",
    "typeof operatori nima?": "Что такое оператор typeof?",
    "JavaScript'da null va undefined farqi?": "В чём разница между null и undefined в JavaScript?",
    "let va const farqi?": "В чём разница между let и const?",
    "JavaScript'da string nima?": "Что такое string в JavaScript?",
    "JavaScript'da == va === farqi?": "В чём разница между == и === в JavaScript?",

    # ---- session 61: HTML/CSS advanced + portfolio projects ----
    "HTML/CSS Portfolio nima?": "Что такое HTML/CSS-портфолио?",
    "Hero section nima?": "Что такое hero-секция?",
    "font-face nima?": "Что такое font-face?",
    "CSS scroll-behavior: smooth nima?": "Что такое CSS scroll-behavior: smooth?",
    "position: sticky nima?": "Что такое position: sticky?",
    "CSS clip-path nima?": "Что такое CSS clip-path?",
    "backdrop-filter nima?": "Что такое backdrop-filter?",
    "CSS custom scroll nima?": "Что такое кастомный CSS-скролл?",
    "Restaurant menu nima?": "Что такое меню ресторана (страница)?",
    "CSS grid auto-rows nima?": "Что такое CSS grid auto-rows?",
    "aspect-ratio: 4/3 nima?": "Что такое aspect-ratio: 4/3?",
    "Food card hover nima?": "Что такое hover-эффект карточки блюда?",
    "CSS counter nima?": "Что такое CSS-счётчик (counter)?",
    "@font-face src: local() nima?": "Что такое @font-face src: local()?",
    "CSS shape-outside nima?": "Что такое CSS shape-outside?",
    "Print stylesheet nima?": "Что такое стили для печати (print stylesheet)?",
    "Fashion blog nima?": "Что такое блог о моде?",
    "CSS multi-column nima?": "Что такое многоколоночный CSS (multi-column)?",
    "drop-cap nima?": "Что такое буквица (drop-cap)?",
    "CSS mix-blend-mode nima?": "Что такое CSS mix-blend-mode?",
    "writing-mode nima?": "Что такое writing-mode?",
    "CSS hyphens nima?": "Что такое CSS hyphens?",
    "text-stroke nima?": "Что такое text-stroke?",
    "line-clamp nima?": "Что такое line-clamp?",
    "Tur sayti landing nima?": "Что такое лендинг туристического сайта?",
    "Parallax effect nima?": "Что такое эффект параллакса?",
    "background-attachment: fixed nima?": "Что такое background-attachment: fixed?",
    "CSS animation fill-mode nima?": "Что такое CSS animation-fill-mode?",
    "Destination card nima?": "Что такое карточка направления (destination card)?",
    "CSS column-gap nima?": "Что такое CSS column-gap?",
    "Hero video background nima?": "Что такое видео-фон hero-секции?",
    "Sticky CTA button nima?": "Что такое липкая CTA-кнопка (sticky CTA button)?",
    "Event/Conference landing nima?": "Что такое лендинг мероприятия/конференции?",
    "CSS countdown nima?": "Что такое CSS-таймер обратного отсчёта?",
    "Ticket pricing nima?": "Что такое цены на билеты (ticket pricing)?",
    "CSS perspective nima?": "Что такое CSS perspective?",
    "Speakers section nima?": "Что такое секция спикеров?",
    "CSS scroll-snap nima?": "Что такое CSS scroll-snap?",
    "Countdown JS nima?": "Что такое таймер обратного отсчёта на JS?",
    "hover card flip nima?": "Что такое переворот карточки при наведении (hover card flip)?",
    "Capstone HTML/CSS loyiha nima?": "Что такое итоговый (capstone) проект HTML/CSS?",
    "Minimal loyiha talablari nima?": "Каковы минимальные требования к проекту?",
    "CSS design token nima?": "Что такое CSS дизайн-токен?",
    "Performant CSS nima?": "Что такое производительный (performant) CSS?",
    "CSS hujjatlashtirish nima?": "Что такое документирование CSS?",
    "Cross-browser test nima?": "Что такое кроссбраузерное тестирование?",
    "GitHub Pages HTML/CSS deploy nima?": "Что такое деплой HTML/CSS на GitHub Pages?",
    "Portfolio'ga sayt qo'shish nima uchun?": "Зачем добавлять сайт в портфолио?",
    "CSS Animation library nima?": "Что такое библиотека CSS-анимаций?",
    "Keyframe nima?": "Что такое keyframe?",
    "animation-delay nima?": "Что такое animation-delay?",
    "animation-play-state nima?": "Что такое animation-play-state?",
    "Custom easing nima?": "Что такое пользовательский easing (custom easing)?",
    "animation-composition nima?": "Что такое animation-composition?",
    "scroll-linked animations nima?": "Что такое анимации, связанные со скроллом (scroll-linked)?",
    "CSS Houdini nima?": "Что такое CSS Houdini?",
    "SaaS landing v2 nima?": "Что такое SaaS-лендинг v2?",
    "Bento grid nima?": "Что такое bento-сетка (bento grid)?",
    "CSS perspective-origin nima?": "Что такое CSS perspective-origin?",
    "Glassmorphism nima?": "Что такое глассморфизм (Glassmorphism)?",
    "Neumorphism nima?": "Что такое неоморфизм (Neumorphism)?",
    "CSS :focus-within nima?": "Что такое CSS :focus-within?",
    "CSS accent-color nima?": "Что такое CSS accent-color?",
    "color-scheme nima?": "Что такое color-scheme?",
    "Portfolio v2 nima?": "Что такое портфолио v2?",
    "CSS custom cursor nima?": "Что такое кастомный курсор CSS?",
    "Page transition nima?": "Что такое переход между страницами (page transition)?",
    "Micro-animation nima?": "Что такое микро-анимация?",
    "CSS @property nima?": "Что такое CSS @property?",
    "Canvas particle animation nima?": "Что такое анимация частиц на Canvas?",
    "Noise/grain texture CSS nima?": "Что такое текстура шума/зерна (noise/grain) в CSS?",
    "Motion path animation nima?": "Что такое анимация по траектории (motion path)?",
    "Tech Startup landing nima?": "Что такое лендинг технологического стартапа?",
    "Animated gradient background nima?": "Что такое анимированный градиентный фон?",
    "CSS neon glow nima?": "Что такое неоновое свечение (neon glow) в CSS?",
    "Typewriter effect CSS nima?": "Что такое эффект печатной машинки (typewriter) в CSS?",
    "Feature comparison table nima?": "Что такое сравнительная таблица возможностей?",
    "CSS grid subgrid nima?": "Что такое CSS grid subgrid?",
    "Animated counter nima?": "Что такое анимированный счётчик?",
    "Dark/Light toggle nima?": "Что такое переключатель тёмной/светлой темы?",
    "Charity/NGO landing nima?": "Что такое лендинг благотворительной организации/НКО?",
    "Impact number animation nima?": "Что такое анимация впечатляющих цифр (impact number)?",
    "Donate button CTA nima?": "Что такое CTA-кнопка пожертвования (donate)?",
    "Accessible color contrast nima?": "Что такое доступный цветовой контраст?",
    "Team section nima?": "Что такое секция команды?",
    "Progress bar (thermometer) nima?": "Что такое индикатор прогресса (thermometer)?",
    "CSS scroll-timeline nima?": "Что такое CSS scroll-timeline?",
    "aria-live region nima?": "Что такое aria-live-регион?",
    "Agency/Studio landing nima?": "Что такое лендинг агентства/студии?",
    "CSS mix-blend-mode: multiply nima?": "Что такое CSS mix-blend-mode: multiply?",
    "overflow: clip nima?": "Что такое overflow: clip?",
    "CSS :has() selector nima?": "Что такое CSS-селектор :has()?",
    "Container query nima?": "Что такое контейнерный запрос (container query)?",
    "scroll-driven animations nima?": "Что такое анимации, управляемые скроллом (scroll-driven)?",
    "CSS @layer nima?": "Что такое CSS @layer?",
    "CSS env() nima?": "Что такое CSS env()?",
    "Product landing page nima?": "Что такое лендинг продукта?",
    "CSS gradient text nima?": "Что такое градиентный текст в CSS?",
    "Testimonial slider nima?": "Что такое слайдер отзывов (testimonial slider)?",
    "Feature list nima?": "Что такое список возможностей (feature list)?",
    "CSS grid masonry nima?": "Что такое CSS grid masonry?",
    "video autoplay muted nima?": "Что такое video autoplay muted?",
    "CSS filter: grayscale() nima?": "Что такое CSS filter: grayscale()?",
    "scroll-margin-top nima?": "Что такое scroll-margin-top?",
}

# ─────────────────────────────────────────────────────────────────────────
# OPTION_MAP: option text (uz) -> option text_ru. Shared across all three
# sessions since many distractor options repeat verbatim (numbers, code
# literals, "CSS grid", "Bir xil", etc). Code/number/literal values are
# mapped to themselves (not natural-language, nothing to translate).
# ─────────────────────────────────────────────────────────────────────────
OPTION_MAP: dict[str, str] = {
    # ---- session 58: Python fundamentals ----
    "Bjarne Stroustrup": "Бьярне Страуструп",
    "James Gosling": "Джеймс Гослинг",
    "Dennis Ritchie": "Деннис Ритчи",
    "Guido van Rossum": "Гвидо ван Россум",
    "*.java": "*.java", "*.py": "*.py", "*.rb": "*.rb", "*.js": "*.js",
    "/* kommentariy */": "/* комментарий */",
    "<!-- kommentariy -->": "<!-- комментарий -->",
    "# kommentariy": "# комментарий",
    "//kommentariy": "//комментарий",
    "Fayl yaratadi": "Создаёт файл",
    "Ma'lumot saqlaydi": "Сохраняет данные",
    "Konsolga chiqaradi": "Выводит в консоль",
    "Animatsiya qo'shadi": "Добавляет анимацию",
    "Ko'rinish uchun": "Для красоты",
    "Tezlik uchun": "Для скорости",
    "Animatsiya uchun": "Для анимации",
    "Kod blokini belgilash (Python bu yerda { } o'rniga ishlatadi)": "Для обозначения блока кода (Python использует их вместо { })",
    "Bog'lash": "Связывание",
    "Yig'ish": "Сборка",
    "Kompilyatsiya": "Компиляция",
    "Kod birdan bajariladi, kompilyatsiya yo'q": "Код выполняется построчно, без компиляции",
    "Bir xil": "Одинаковые",
    "Python 2 yangi": "Python 2 новее",
    "Python 3 yangi, print() funksiya, Unicode standart": "Python 3 новее, print() — функция, Unicode по умолчанию",
    "Ikkalasi bir xil": "Они одинаковые",
    "1 dan 5 gacha": "От 1 до 5",
    "0 dan 4 gacha bo'lgan son ketma-ketligi": "Последовательность чисел от 0 до 4",
    "5 ta bo'sh element": "5 пустых элементов",
    "5 ta sonli ro'yxat [1,2,3,4,5]": "Список из 5 чисел [1,2,3,4,5]",
    "Mantiqiy qiymat": "Логическое значение",
    "Butun son": "Целое число",
    "Matn": "Текст",
    "Kasr son": "Дробное число",
    "Ro'yxat": "Список",
    "None": "None",
    "Raqam 42": "Число 42",
    "True": "True",
    "'42' matni": "Строка '42'",
    "0": "0",
    "Qiymat yo'qligini ifodalovchi ob'ekt": "Объект, обозначающий отсутствие значения",
    "Bo'sh satr": "Пустая строка",
    "False": "False",
    "10": "10", "7": "7", "3": "3", "13": "13",
    "<class 'float'>": "<class 'float'>",
    "<class 'bool'>": "<class 'bool'>",
    "<class 'str'>": "<class 'str'>",
    "<class 'int'>": "<class 'int'>",
    "0 va 1": "0 и 1",
    "'rost' va 'yolg'on'": "'истина' и 'ложь'",
    "1 va -1": "1 и -1",
    "True va False": "True и False",
    "10.0": "10.0",
    "'10'": "'10'",
    "Xato": "Ошибка",
    "satr = [text]": "satr = [text]",
    "satr = 'text' yoki satr = \"text\"": "satr = 'text' или satr = \"text\"",
    "satr = {text}": "satr = {text}",
    "satr = (text)": "satr = (text)",
    "len(satr)": "len(satr)",
    "satr.count()": "satr.count()",
    "satr.size()": "satr.size()",
    "satr.length": "satr.length",
    "satr[1:3]": "satr[1:3]",
    "satr(1,3)": "satr(1,3)",
    "satr.slice(1,3)": "satr.slice(1,3)",
    "satr.cut(1,3)": "satr.cut(1,3)",
    "satr.sort()": "satr.sort()",
    "satr.reverse()": "satr.reverse()",
    "satr.upper()": "satr.upper()",
    "satr.max()": "satr.max()",
    "Funksiya satr": "Строка-функция",
    "f'{variable}' — o'zgaruvchini satr ichiga qo'yish": "f'{variable}' — вставка переменной в строку",
    "Fayl satr": "Файловая строка",
    "Filtr satr": "Строка-фильтр",
    "'herrо'": "'herrо'",
    "'hello'": "'hello'",
    "'herro'": "'herro'",
    "'herlo'": "'herlo'",
    "4": "4",
    "2": "2",
    "'a b c'": "'a b c'",
    "'abc'": "'abc'",
    "['a', 'b', 'c']": "['a', 'b', 'c']",
    "('a','b','c')": "('a','b','c')",
    "Faqat * va /": "Только * и /",
    "Faqat +": "Только +",
    "+ - * / // % **": "+ - * / // % **",
    "Faqat raqamlar": "Только числа",
    "input()": "input()", "scan()": "scan()", "get()": "get()", "read()": "read()",
    "Matnni yuqoriga aylantiradi": "Переводит текст в верхний регистр",
    "Qiymatni butun songa aylantiradi": "Преобразует значение в целое число",
    "Qiymatni satrga aylantiradi": "Преобразует значение в строку",
    "Qiymatni float'ga aylantiradi": "Преобразует значение в float",
    "Ko'paytirish": "Умножение",
    "Darajaga ko'tarish": "Возведение в степень",
    "Butun qism qo'yish (bo'linmaning butun qismi)": "Целочисленное деление (целая часть от деления)",
    "Modul": "Модуль",
    "Bo'lish": "Деление",
    "Bo'lishdan qolgan qoldiq": "Остаток от деления",
    "Foiz": "Процент",
    "Qo'shish": "Сложение",
    "Xotira xatosi": "Ошибка памяти",
    "Tur xatosi": "Ошибка типа",
    "Nolga bo'lish xatosi": "Ошибка деления на ноль",
    "Qiymat xatosi": "Ошибка значения",
    "4.0": "4.0", "3.7": "3.7",
    "else, if, elif": "else, if, elif",
    "if, elif, else": "if, elif, else",
    "elif, if, else": "elif, if, else",
    "else, elif, if": "else, elif, if",
    "and, or, not bilan birlashtirilgan ko'p shart": "Несколько условий, объединённых с помощью and, or, not",
    "Bitta shart": "Одно условие",
    "if-else bloki": "Блок if-else",
    "Siklga bog'liq shart": "Условие, связанное с циклом",
    "'0 < x < 10'": "'0 < x < 10'",
    "'x > 0 or x < 10'": "'x > 0 or x < 10'",
    "'0 < x > 10'": "'0 < x > 10'",
    "'x != 0 and x != 10'": "'x != 0 and x != 10'",
    "Elementning ketma-ketlik ichida bor-yo'qligini tekshiradi": "Проверяет наличие элемента в последовательности",
    "if condition: value else other": "if condition: value else other",
    "condition ? value : other": "condition ? value : other",
    "value when condition else other": "value when condition else other",
    "value if condition else other": "value if condition else other",
    "Faqat bir marta": "Только один раз",
    "if sharti False bo'lganda": "Когда условие if ложно",
    "Hech qachon": "Никогда",
    "Har doim": "Всегда",
    "for i = 0; i<n; i++": "for i = 0; i<n; i++",
    "loop i in n:": "loop i in n:",
    "for(i; n; i++)": "for(i; n; i++)",
    "for i in range(n):": "for i in range(n):",
    "Bir marta bajariladi": "Выполняется один раз",
    "Har doim bajariladi": "Выполняется всегда",
    "for turi": "Разновидность for",
    "Shart True bo'lgunicha takrorlanadi": "Повторяется, пока условие истинно",
    "Ro'yxatni tartiblaydi": "Сортирует список",
    "Indeks va qiymat juftini qaytaradi": "Возвращает пары индекс-значение",
    "Ro'yxatni filterlaydi": "Фильтрует список",
    "Ro'yxatni bo'sh qiladi": "Опустошает список",
    "Ikki yoki ko'p iterable'ni juftlab qaytaradi": "Объединяет два или больше итерируемых объектов попарно",
    "Fayl arxivlash": "Архивирование файла",
    "O'zgaruvchi yaratadi": "Создаёт переменную",
    "Siklardan chiqadi": "Выходит из цикла",
    "Sikl boshiga qaytadi": "Возвращается к началу цикла",
    "Joriy iteratsiyani o'tkazib keyingisiga": "Пропускает текущую итерацию и переходит к следующей",
    "Boshiga qaytadi": "Возвращается к началу",
    "O'zgaruvchi o'chiradi": "Удаляет переменную",
    "Keyingi iteratsiya": "Переходит к следующей итерации",
    "Siklardan butunlay chiqadi": "Полностью выходит из цикла",
    "Sikl break bilan emas, tabiiy tugasa bajariladigan blok": "Блок, который выполняется, если цикл завершился естественно, а не через break",
    "Faqat break bilan": "Только при break",
    "Bitta sikl": "Один цикл",
    "Bitta iteratsiya": "Одна итерация",
    "Rekursiv funksiya": "Рекурсивная функция",
    "Sikl ichidagi sikl": "Цикл внутри цикла",
    "Noyob elementlar": "Уникальные элементы",
    "O'zgarmas to'plam": "Неизменяемая коллекция",
    "O'zgartirish mumkin bo'lgan tartibli elementlar to'plami": "Изменяемая упорядоченная коллекция элементов",
    "Kalit-qiymat": "Ключ-значение",
    "O'zgarmas tartibli elementlar to'plami": "Неизменяемая упорядоченная коллекция элементов",
    "O'zgartirish mumkin to'plam": "Изменяемая коллекция",
    "List o'zgartirish mumkin (mutable), tuple o'zgartirish mumkin emas (immutable)": "Список изменяемый (mutable), кортеж неизменяемый (immutable)",
    "List immutable": "Список неизменяемый",
    "Tuple o'zgartirish mumkin": "Кортеж изменяемый",
    "extend bitta element": "extend добавляет один элемент",
    "append bitta element, extend ko'p element (iterable) qo'shadi": "append добавляет один элемент, extend — несколько (итерируемый объект)",
    "append iterable qo'shadi": "append добавляет итерируемый объект",
    "sort() aslini o'zgartiradi, sorted() yangi ro'yxat qaytaradi": "sort() изменяет исходный список, sorted() возвращает новый список",
    "sort() yangi qaytaradi": "sort() возвращает новый",
    "sorted() aslini o'zgartiradi": "sorted() изменяет исходный",
    "Tuple birlashtirish": "Объединение кортежей",
    "Tuple yaratish": "Создание кортежа",
    "a, b = (1, 2) kabi qiymatlarni o'zgaruvchilarga chiqarish": "Присвоение значений переменным, как в a, b = (1, 2)",
    "Tuple filterlash": "Фильтрация кортежа",
    "Ro'yxatning yarmi": "Половина списка",
    "Ro'yxat boshidan": "Список с начала",
    "Ro'yxatni teskari tartibda olish": "Получение списка в обратном порядке",
    "Bo'sh ro'yxat": "Пустой список",
    "Oxirgi elementni oladi": "Забирает последний элемент",
    "Birinchi elementni olib tashlaydi va qaytaradi": "Удаляет и возвращает первый элемент",
    "Birinchi elementni qo'shadi": "Добавляет первый элемент",
    "Ro'yxatni to'xtatadi": "Останавливает список",
    "dict": "dict", "tuple": "tuple", "set": "set", "list": "list",
    "Takrorlash bo'lmaydi, har element faqat bir marta": "Повторов нет, каждый элемент встречается только один раз",
    "Indeks bilan": "С индексом",
    "Bir xil elementlar": "Одинаковые элементы",
    "Tartiblangan": "Упорядоченные",
    "Set'dan o'chiradi": "Удаляет из множества",
    "Set'ni qaytaradi": "Возвращает множество",
    "Set'ni tozalaydi": "Очищает множество",
    "Set'ga element qo'shadi": "Добавляет элемент в множество",
    "Simmetrik farq": "Симметрическая разность",
    "Ikki to'plamning umumiy elementlari": "Общие элементы двух множеств",
    "Farq": "Разность",
    "Birlashtirish": "Объединение",
    "Yo'q": "Нет",
    "Set yaxshi": "Set лучше",
    "Tuple yaxshi": "Tuple лучше",
    "Ha, tartib va takrorlash muhim": "Да, важны порядок и повторы",
    "Ro'yxat kopiyasi": "Копия списка",
    "Bir qatorda ro'yxat yaratish: [x for x in range(10)]": "Создание списка в одну строку: [x for x in range(10)]",
    "Ro'yxat haqida matn": "Текст о списке",
    "Ro'yxatni o'chirish": "Удаление списка",
    "Kamayish tartibida": "По убыванию",
    "Tasodifiy tartibda": "В случайном порядке",
    "O'sish tartibida": "По возрастанию",
    "Asl tartibda": "В исходном порядке",
    "Tezroq aslida": "На самом деле быстрее",
    "Bir xil tezlikda": "С одинаковой скоростью",
    "List tartibli, set hash asosida O(1) qidiruv": "Список упорядоченный (линейный поиск), а set использует хеш и ищет за O(1)",
    "Set sekinroq": "Set медленнее",
    "def myFunc():": "def myFunc():",
    "define myFunc():": "define myFunc():",
    "func myFunc():": "func myFunc():",
    "function myFunc():": "function myFunc():",
    "Funksiya chaqiruvida beriladigan qiymatlar": "Значения, передаваемые при вызове функции",
    "Funksiya ichidagi o'zgaruvchilar": "Переменные внутри функции",
    "Funksiya qaytaruvchi qiymatlar": "Значения, которые возвращает функция",
    "Funksiya nomlari": "Имена функций",
    "Ixtiyoriy miqdordagi positional argumentlar": "Произвольное количество позиционных аргументов",
    "Bitta argument": "Один аргумент",
    "Majburiy argument": "Обязательный аргумент",
    "Kalit-qiymat argumentlar": "Аргументы ключ-значение",
    "Ixtiyoriy miqdordagi kalit-qiymat argumentlar": "Произвольное количество именованных аргументов (ключ-значение)",
    "Positional argumentlar": "Позиционные аргументы",
    "Ismsiz birsatirli funksiya: lambda x: x*2": "Безымянная однострочная функция: lambda x: x*2",
    "Generator funksiya": "Функция-генератор",
    "Katta funksiya": "Большая функция",
    "O'zgaruvchi qayerda ko'rinishi (lokal, global)": "Где видна переменная (локальная, глобальная)",
    "Funksiya nomi": "Имя функции",
    "Argument turi": "Тип аргумента",
    "Fayl hajmi": "Размер файла",
    "Global funksiya yaratadi": "Создаёт глобальную функцию",
    "Yangi global o'zgaruvchi": "Новую глобальную переменную",
    "Funksiya ichida global o'zgaruvchini o'zgartirishga ruxsat beradi": "Позволяет изменять глобальную переменную внутри функции",
    "Funksiyaning o'zini chaqirishi": "Функция вызывает саму себя",
    "Sikllar": "Циклы",
    "Bitta marta chaqirish": "Однократный вызов",
    "open('file','r')": "open('file','r')",
    "File.read('file')": "File.read('file')",
    "file.open('file')": "file.open('file')",
    "read('file')": "read('file')",
    "Faylni avtomatik yopuvchi kontekst menejeri": "Контекстный менеджер, автоматически закрывающий файл",
    "Faylni yashiradi": "Скрывает файл",
    "Faylni nusxalaydi": "Копирует файл",
    "Faylni o'chiradi": "Удаляет файл",
    "Shart turi": "Вид условия",
    "Funksiya turi": "Вид функции",
    "Xatolarni tutib boshqarish": "Перехват и обработка ошибок",
    "Sikl turi": "Вид цикла",
    "Har qanday xatoni e o'zgaruvchisida ushlaydi": "Перехватывает любую ошибку в переменную e",
    "Xatoni ko'rsatmaydi": "Не показывает ошибку",
    "Faqat bitta xato turi": "Только один тип ошибки",
    "Xatoni bekor qiladi": "Отменяет ошибку",
    "Faqat muvaffaqiyatli": "Только при успехе",
    "Xato bo'lsin-bo'lmasin har doim bajariladi": "Выполняется всегда, независимо от ошибки",
    "Xato bo'lganda": "При ошибке",
    "Xatoni tushuntiradi": "Объясняет ошибку",
    "Xatoni qayta yoki yangi xato chiqaradi": "Вызывает повторную или новую ошибку",
    "Xatoni qaytaradi": "Возвращает ошибку",
    "Xatoni yashiradi": "Скрывает ошибку",
    "Ruxsat xatosi": "Ошибка доступа",
    "Fayl topilmagan xatosi": "Ошибка \"файл не найден\"",
    "Standart xato": "Стандартная ошибка",
    "Exception'dan meros olgan o'z xato sinfingiz": "Собственный класс ошибки, унаследованный от Exception",
    "Python xatosi": "Ошибка Python",
    "Tizim xatosi": "Системная ошибка",
    "Modul turi": "Вид модуля",
    "Paket turi": "Вид пакета",
    "Ob'ektlar uchun qolip (blueprint)": "Шаблон (blueprint) для объектов",
    "Konstruktor — ob'ekt yaratilganda chaqiriladigan metod": "Конструктор — метод, вызываемый при создании объекта",
    "Sinf metodi": "Метод класса",
    "Dasturni boshlaydi": "Запускает программу",
    "Destruktor": "Деструктор",
    "Global o'zgaruvchi": "Глобальная переменная",
    "Sinfning joriy nusxasiga havola": "Ссылка на текущий экземпляр класса",
    "Statik metod": "Статический метод",
    "Sinf attributi": "Атрибут класса",
    "Farzand sinf ota-sinfning xususiyat va metodlarini oladi": "Дочерний класс получает свойства и методы родительского класса",
    "Fayl nusxalash": "Копирование файла",
    "Modul nusxalash": "Копирование модуля",
    "Paket nusxalash": "Копирование пакета",
    "Yuqori sinf": "Верхний класс",
    "Ota-sinf metodlariga murojaat": "Обращение к методам родительского класса",
    "Past sinf": "Нижний класс",
    "Ko'p konstruktor": "Много конструкторов",
    "Ko'p meros": "Множественное наследование",
    "Ko'p sinf": "Много классов",
    "Bir metod ismi turli sinflarda turlicha ishlashi": "Один и тот же метод работает по-разному в разных классах",
    "Xususiy metod": "Приватный метод",
    "Sinfga tegishli metod (self o'rniga cls)": "Метод, относящийся к классу (cls вместо self)",
    "Oddiy metod": "Обычный метод",
    "Global metod": "Глобальный метод",
    "Sinf yoki nusxaga bog'liq bo'lmagan metod": "Метод, не привязанный ни к классу, ни к экземпляру",
    "O(n)": "O(n)", "O(log n)": "O(log n)",
    "O(1) — hash asosida": "O(1) — на основе хеша",
    "O(n²)": "O(n²)",
    "dictionary.insert('word','trans')": "dictionary.insert('word','trans')",
    "dictionary['word'] = 'trans'": "dictionary['word'] = 'trans'",
    "dictionary.set('word','trans')": "dictionary.set('word','trans')",
    "dictionary.add('word','trans')": "dictionary.add('word','trans')",
    "JSON matn formati, dict Python ob'ekti": "JSON — текстовый формат, dict — объект Python",
    "JSON Python ob'ekti": "JSON — объект Python",
    "Dict matn formati": "Dict — текстовый формат",
    "Bo'sh dict": "Пустой dict",
    "O'zgarmas dict": "Неизменяемый dict",
    "Oddiy dict": "Обычный dict",
    "Mavjud bo'lmagan kalit uchun standart qiymat yaratuvchi dict": "dict, создающий значение по умолчанию для отсутствующего ключа",
    "dictionary.save(file)": "dictionary.save(file)",
    "json.dump(dictionary, file)": "json.dump(dictionary, file)",
    "print(dictionary)": "print(dictionary)",
    "file.write(dictionary)": "file.write(dictionary)",
    "[('b',1)]": "[('b',1)]",
    "[('b',1),('a',3)]": "[('b',1),('a',3)]",
    "[('a',3)]": "[('a',3)]",
    "[('a',3),('b',1)]": "[('a',3),('b',1)]",
    "del dict[key]": "del dict[key]",
    "dict.remove(key)": "dict.remove(key)",
    "del dict.key": "del dict.key",
    "dict.pop(key, None)": "dict.pop(key, None)",
    "JavaScript fayl": "Файл JavaScript",
    "CSS fayl": "Файл CSS",
    "HTML fayl": "Файл HTML",
    "Python kodi bo'lgan .py fayl": "Файл .py с кодом Python",
    "Modulni joriy muhitga yuklash": "Загружает модуль в текущее окружение",
    "Ma'lumot olish": "Получение данных",
    "Animatsiya": "Анимация",
    "Modul nomi o'zgartirish": "Изменение имени модуля",
    "Moduldan faqat belgilangan narsani import qilish": "Импорт только указанного из модуля",
    "Modulni o'chirish": "Удаление модуля",
    "Barcha yuklash": "Загрузка всего",
    "Ma'lumotlar bazasi": "База данных",
    "__init__.py bo'lgan papka (modullar to'plami)": "Папка с __init__.py (набор модулей)",
    "Zip arxiv": "Zip-архив",
    "Bitta fayl": "Один файл",
    "Python Ide": "Python IDE",
    "Python Integration": "Python Integration",
    "Python Interpreter": "Python Interpreter",
    "Python Package Index — paketlar ombori": "Python Package Index — хранилище пакетов",
    "CSS vositasi": "Инструмент CSS",
    "Brauzer": "Браузер",
    "HTML generator": "Генератор HTML",
    "Python paket menejeri": "Менеджер пакетов Python",
    "requests": "requests", "numpy": "numpy", "flask": "flask", "os": "os",
    "Loyiha uchun alohida Python paket muhiti yaratish": "Для создания изолированной среды пакетов для проекта",
    "CSS uchun": "Для CSS",
    "Server uchun": "Для сервера",
    "Tartibli ro'yxat": "Упорядоченный список",
    "Kalit-qiymat juftlari to'plami": "Набор пар ключ-значение",
    "dict[key] yo'q bo'lsa KeyError, get() None qaytaradi": "Если dict[key] нет — KeyError, get() возвращает None",
    "dict[] None qaytaradi": "dict[] возвращает None",
    "get() KeyError beradi": "get() выдаёт KeyError",
    "(kalit, qiymat) juftlari ko'rinishi": "Представление в виде пар (ключ, значение)",
    "Lug'atni o'chiradi": "Удаляет словарь",
    "Faqat qiymatlar": "Только значения",
    "Faqat kalitlar": "Только ключи",
    "Noyob immutable elementlar to'plami": "Коллекция уникальных неизменяемых элементов",
    "Kalitni olib tashlaydi va qiymatini qaytaradi": "Удаляет ключ и возвращает его значение",
    "Kalit qo'shadi": "Добавляет ключ",
    "Qiymatni yangilaydi": "Обновляет значение",
    "Barcha kalitlarni o'chiradi": "Удаляет все ключи",
    "O'zgartirish mumkin set": "Изменяемый set",
    "Katta set": "Большой set",
    "O'zgarmas set (lug'at kaliti sifatida ishlatilishi mumkin)": "Неизменяемый set (может использоваться как ключ словаря)",
    "Bo'sh set": "Пустой set",
    "Faqat bir kalit qo'shadi": "Добавляет только один ключ",
    "Lug'atni tartiblaydi": "Сортирует словарь",
    "Boshqa lug'at yoki juftlik bilan yangilaydi": "Обновляет данными из другого словаря или пар ключ-значение",
    "Python sinf": "Класс Python",
    "collections.Counter — element sonini hisoblash uchun": "collections.Counter — для подсчёта количества элементов",
    "O'zgaruvchi soni": "Количество переменных",
    "Raqamlar hisoblash": "Подсчёт чисел",

    # ---- session 59: JavaScript ----
    "Array tartiblaydi": "Сортирует массив",
    "Array filterlaydi": "Фильтрует массив",
    "Indeks bo'yicha element qaytaradi (manfiy ham ishlaydi)": "Возвращает элемент по индексу (работает и с отрицательными)",
    "Array uzunligini beradi": "Возвращает длину массива",
    "Ob'ektning chuqur klonini yaratadi": "Создаёт глубокую копию объекта",
    "Ob'ektni o'chiradi": "Удаляет объект",
    "Sayoz nusxa": "Поверхностная копия",
    "Ob'ektni tartiblaydi": "Сортирует объект",
    "Ob'ektning o'z xususiyati bor-yo'qligini tekshiradi": "Проверяет, есть ли у объекта собственное свойство",
    "Xususiyat qiymatini qaytaradi": "Возвращает значение свойства",
    "Xususiyatni o'chiradi": "Удаляет свойство",
    "Ob'ektga xususiyat qo'shadi": "Добавляет свойство объекту",
    "Funksiya": "Функция",
    "Mahalliy o'zgaruvchi": "Локальная переменная",
    "Modul": "Модуль",
    "Har qanday muhitda global ob'ektga havola": "Ссылка на глобальный объект в любой среде",
    "Birinchi xato": "Первая ошибка",
    "Barcha promiselar bajarilganida (muvaffaqiyatli va xato ham) natijalar": "Результаты всех промисов после завершения (как успешных, так и с ошибкой)",
    "Barcha muvaffaqiyatli": "Все успешные",
    "Birinchi muvaffaqiyatli": "Первый успешный",
    "find qiymat bo'yicha qidiradi, at indeks bo'yicha oladi": "find ищет по значению, at получает по индексу",
    "at qidiradi": "at ищет",
    "find indeks bo'yicha": "find по индексу",
    "Mantiqiy operatorlar": "Логические операторы",
    "Tenglik operatorlari": "Операторы равенства",
    "Solishtirish operatorlari": "Операторы сравнения",
    "Qisqartirilgan mantiqiy tayinlash operatorlari": "Сокращённые операторы логического присваивания",
    "Aslini o'zgartiradi": "Изменяет исходный массив",
    "Array tekislaydi": "Выравнивает массив",
    "Aslini o'zgartirmay yangi tartiblangan array qaytaradi": "Возвращает новый отсортированный массив, не изменяя исходный",
    "find() birinchi mos qiymat, filter() barcha mos qiymatlar": "find() возвращает первое совпадение, filter() — все совпадения",
    "filter() birinchi mos": "filter() первое совпадение",
    "find() barcha mos": "find() все совпадения",
    "Array nusxalaydi": "Копирует массив",
    "Ichma-ich arrayni tekislashtiradi": "Разворачивает вложенный массив в плоский",
    "Birinchi mos elementning indeksini qaytaradi (-1 agar yo'q)": "Возвращает индекс первого совпадающего элемента (-1, если не найден)",
    "Qiymatni qaytaradi": "Возвращает значение",
    "Barcha indekslarni qaytaradi": "Возвращает все индексы",
    "Boolean qaytaradi": "Возвращает boolean",
    "Birinchi mos qaytaradi": "Возвращает первое совпадение",
    "Bir element tekshiradi": "Проверяет один элемент",
    "Soni qaytaradi": "Возвращает количество",
    "Barcha elementlar shartni qondirsa true": "true, если все элементы удовлетворяют условию",
    "Hech biri mos kelmasa true": "true, если ни один не подходит",
    "Barcha elementlar tekshiradi": "Проверяет все элементы",
    "Kamida bitta element shartni qondirsa true": "true, если хотя бы один элемент удовлетворяет условию",
    "[1,2,3,4,5]": "[1,2,3,4,5]", "[]": "[]",
    "[5,4,3,2,1]": "[5,4,3,2,1]", "[0,1,2,3,4]": "[0,1,2,3,4]",
    "map + flat — har elementga map qo'llab natijani tekislashtiradi": "map + flat — применяет map к каждому элементу и разворачивает результат",
    "filter + flat": "filter + flat", "sort + flat": "sort + flat", "flat + reverse": "flat + reverse",
    "a va b ni filterlaydi": "Фильтрует a и b",
    "a va b ni tartiblaydi": "Сортирует a и b",
    "a va b ni bitta yangi arrayga birlashtiradi": "Объединяет a и b в один новый массив",
    "a va b ni o'chiradi": "Удаляет a и b",
    "Server tomonida saqlash": "Хранение на стороне сервера",
    "Brauzerda doimiy kalit-qiymat saqlash": "Постоянное хранение ключ-значение в браузере",
    "Cookie saqlash": "Хранение cookie",
    "Session saqlash": "Хранение сессии",
    "Qiymatni oladi": "Получает значение",
    "Barcha ma'lumotlarni o'chiradi": "Удаляет все данные",
    "Kalit-qiymat juftini saqlaydi": "Сохраняет пару ключ-значение",
    "Kalit bo'yicha qiymatni qaytaradi": "Возвращает значение по ключу",
    "Qiymat saqlaydi": "Сохраняет значение",
    "Barcha kalitlarni qaytaradi": "Возвращает все ключи",
    "localStorage doimiy (brauzer yopilsa ham), sessionStorage brauzer yopilganda yo'qoladi": "localStorage постоянный (сохраняется даже при закрытии браузера), sessionStorage исчезает при закрытии браузера",
    "localStorage sessiyaviy": "localStorage сессионный",
    "sessionStorage doimiy": "sessionStorage постоянный",
    "Ha, faqat boolean": "Да, только boolean",
    "Yo'q, har qanday tur": "Нет, любой тип",
    "Ha, JSON.stringify/parse bilan ob'ektlarni saqlash kerak": "Да, объекты нужно сохранять через JSON.stringify/parse",
    "Ha, faqat raqam": "Да, только числа",
    "Kalit bo'yicha yozuvni o'chiradi": "Удаляет запись по ключу",
    "Sahifani yangilaydi": "Обновляет страницу",
    "Brauzer sessiyasini o'chiradi": "Удаляет сессию браузера",
    "Barcha localStorage'ni tozalaydi": "Полностью очищает localStorage",
    "Bitta yozuv o'chiradi": "Удаляет одну запись",
    "1 KB": "1 KB", "Cheksiz": "Безлимитный",
    "5-10 MB (brauzerga qarab)": "5-10 МБ (зависит от браузера)",
    "1 GB": "1 GB",
    "Ikkala ob'ektni o'chiradi": "Удаляет оба объекта",
    "Ob'ektlarni tartiblaydi": "Сортирует объекты",
    "Ikkala ob'ekt xususiyatlarini yangi ob'ektga birlashtiradi": "Объединяет свойства обоих объектов в новый объект",
    "Ob'ektlarni filterlaydi": "Фильтрует объекты",
    "Array filterlash": "Фильтрация массива",
    "Array o'chirish": "Удаление массива",
    "Array yaratish": "Создание массива",
    "Array elementlarini o'zgaruvchilarga chiqarish": "Присвоение элементов массива переменным",
    "[kalit, qiymat] juftlari arrayini qaytaradi": "Возвращает массив пар [ключ, значение]",
    "Map'da faqat satr kalit": "В Map ключ — только строка",
    "Map'da ixtiyoriy tur kalit bo'lishi mumkin, ob'ektda faqat satr": "В Map ключом может быть любой тип, в объекте — только строка",
    "Ob'ektda ixtiyoriy tur kalit": "В объекте ключ любого типа",
    "Noyob qiymatlar to'plami": "Коллекция уникальных значений",
    "Array turi": "Разновидность массива",
    "Ob'ekt turi": "Разновидность объекта",
    "Elementni qaytaradi": "Возвращает элемент",
    "Elementning Set'da bor-yo'qligini boolean qaytaradi": "Возвращает boolean, есть ли элемент в Set",
    "Elementni qo'shadi": "Добавляет элемент",
    "Elementni o'chiradi": "Удаляет элемент",
    "Map kalitlari ob'ekt uchun": "Ключи Map для объектов",
    "WeakMap kalitlari faqat ob'ekt, zaiif havolalar (GC uchun)": "Ключи WeakMap — только объекты, слабые ссылки (для сборщика мусора)",
    "WeakMap barcha tur uchun": "WeakMap для всех типов",
    "Noyob va o'zgarmas ibtidoiy qiymat": "Уникальное и неизменяемое примитивное значение",
    "Boolean turi": "Тип boolean", "Number turi": "Тип number", "String turi": "Тип string",
    "HTML shablon": "Шаблон HTML",
    "Backtick orqali satr interpolatsiyasi va ko'p qatorli satrlar": "Интерполяция строк и многострочные строки через обратные кавычки",
    "Shablonli CSS": "Шаблонный CSS",
    "JavaScript shablon": "Шаблон JavaScript",
    "Yangi array yaratadi": "Создаёт новый массив",
    "Har bir element uchun funksiya chaqiradi, hech narsa qaytarmaydi": "Вызывает функцию для каждого элемента, ничего не возвращает",
    "Array o'chiradi": "Удаляет массив",
    "Iterable yoki array-like ob'ektdan yangi array yaratadi": "Создаёт новый массив из итерируемого или array-like объекта",
    "Faqat element turidagi farzandlar HTMLCollection": "HTMLCollection только дочерних элементов",
    "Barcha farzandlar": "Все дочерние узлы",
    "Aka-ukalar": "Соседние элементы",
    "Ota-element": "Родительский элемент",
    "Hodisa to'xtashi": "Остановка события",
    "Hodisa farzanddan ota-elementlarga ko'tarilishi": "Событие поднимается от дочернего элемента к родительским",
    "Hodisa pastga tushishi": "Событие опускается вниз",
    "Ko'p farzandlar o'rniga ota-elementga hodisa tinglovchi qo'yish": "Установка обработчика на родительский элемент вместо множества дочерних",
    "Hodisa yaratish": "Создание события",
    "Hodisani o'chirish": "Удаление события",
    "NodeList ba'zi array metodlarsiz, uni Array.from() bilan array'ga aylantirish mumkin": "У NodeList нет некоторых методов массива, его можно превратить в массив через Array.from()",
    "Array NodeList metodlarsiz": "У Array нет методов NodeList",
    "CSS kuzatuvchi": "Наблюдатель CSS",
    "DOM o'zgarishlarini kuzatuvchi API": "API для отслеживания изменений DOM",
    "Server kuzatuvchi": "Наблюдатель сервера",
    "Animatsiya kuzatuvchi": "Наблюдатель анимации",
    "Farzand elementni ota-elementning oxiriga qo'shadi": "Добавляет дочерний элемент в конец родительского",
    "Elementni almashtiradi": "Заменяет элемент",
    "Elementni nusxalaydi": "Копирует элемент",
    "Ota-elementdan farzand elementni olib tashlaydi": "Удаляет дочерний элемент из родительского",
    "Element qo'shadi": "Добавляет элемент",
    "Elementni ko'chiradi": "Перемещает элемент",
    "Elementni tartiblaydi": "Сортирует элемент",
    "Elementni ko'rsatilgan noddan oldin qo'shadi": "Вставляет элемент перед указанным узлом",
    "Element oxiriga qo'shadi": "Добавляет в конец",
    "Elementning inline matn rangini o'rnatadi": "Задаёт инлайн-цвет текста элемента",
    "Matn o'lchami": "Размер текста",
    "Border rangi": "Цвет границы",
    "Fon rangi": "Цвет фона",
    "Cookie ma'lumotlari": "Данные cookie",
    "Forma ma'lumotlari": "Данные формы",
    "HTML elementidagi data-* atributlariga kirish": "Доступ к атрибутам data-* HTML-элемента",
    "Ma'lumotlar to'plami": "Набор данных",
    "Elementni va barcha bolalarini chuqur nusxalaydi": "Глубоко копирует элемент и всех его потомков",
    "Elementni topadi": "Находит элемент",
    "Elementning barcha bolalarini o'chiradi": "Удаляет всех потомков элемента",
    "Matn qo'shadi": "Добавляет текст",
    "Elementni yashiradi": "Скрывает элемент",
    "Atributni o'chiradi": "Удаляет атрибут",
    "Atributni tekshiradi": "Проверяет атрибут",
    "HTML atributining qiymatini qaytaradi": "Возвращает значение HTML-атрибута",
    "Atributni o'rnatadi": "Устанавливает атрибут",
    "Document Object Model — HTML'ni dasturiy ravishda boshqarish imkonini beruvchi daraxт tuzilmasi": "Document Object Model — древовидная структура, позволяющая программно управлять HTML",
    "JavaScript ob'ekti": "Объект JavaScript",
    "Ma'lumotlar ob'ekti": "Объект данных",
    "CSS ob'ekti": "Объект CSS",
    "Klass bo'yicha element oladi": "Получает элемент по классу",
    "Tag bo'yicha oladi": "Получает по тегу",
    "ID bo'yicha bitta elementni qaytaradi": "Возвращает один элемент по ID",
    "Selektor bo'yicha oladi": "Получает по селектору",
    "textContent HTML": "textContent — HTML",
    "innerHTML faqat matn": "innerHTML — только текст",
    "innerHTML HTML belgilash ham, textContent faqat matn": "innerHTML включает HTML-разметку, textContent — только текст",
    "Klassni almashtiradi": "Заменяет класс",
    "Elementga klass qo'shadi": "Добавляет класс элементу",
    "Klass o'chiradi": "Удаляет класс",
    "Klassni tekshiradi": "Проверяет класс",
    "Foydalanuvchini yo'naltiradi": "Перенаправляет пользователя",
    "Hodisani o'chiradi": "Удаляет событие",
    "Elementga hodisa tinglovchi qo'shadi": "Добавляет обработчик события элементу",
    "Animatsiya to'xtatadi": "Останавливает анимацию",
    "Hodisani chaqiradi": "Вызывает событие",
    "Hodisaning standart harakatini bekor qiladi": "Отменяет стандартное действие события",
    "querySelectorAll bitta": "querySelectorAll — один",
    "querySelector bitta, querySelectorAll barcha mos elementlar": "querySelector — один элемент, querySelectorAll — все подходящие",
    "querySelector barcha": "querySelector — все",
    "Yangi HTML element yaratadi (DOM'ga qo'shilmagan)": "Создаёт новый HTML-элемент (не добавленный в DOM)",
    "Array": "Массив",
    "obj.field yoki obj['field']": "obj.field yoki obj['field']",
    "obj[field]": "obj[field]", "obj::field": "obj::field", "obj->field": "obj->field",
    "obj.key = val": "obj.key = val",
    "obj.insert(key,val)": "obj.insert(key,val)",
    "obj.add(key,val)": "obj.add(key,val)",
    "obj.set(key,val)": "obj.set(key,val)",
    "Juftliklarni qaytaradi": "Возвращает пары",
    "Qiymatlarni qaytaradi": "Возвращает значения",
    "Kalitlar arrayini qaytaradi": "Возвращает массив ключей",
    "Ob'ektning barcha xususiyatlarini yangi ob'ektga nusxalaydi": "Копирует все свойства объекта в новый объект",
    "Ma'lumot yo'qotish": "Потеря данных",
    "Ob'ekt yoki massivdan qiymatlarni o'zgaruvchilarga chiqarish": "Извлечение значений из объекта или массива в переменные",
    "Massiv yaratish": "Создание массива",
    "Ob'ekt yaratish": "Создание объекта",
    "Faylni yuklaydi": "Загружает файл",
    "JavaScript ob'ektini JSON matnga aylantiradi": "Преобразует объект JavaScript в строку JSON",
    "JSON parse qiladi": "Парсит JSON",
    "Ob'ektni satrlaydi": "Преобразует объект в строку",
    "JSON matnni JavaScript ob'ektiga aylantiradi": "Преобразует строку JSON в объект JavaScript",
    "Faylni saqlaydi": "Сохраняет файл",
    "function = name() {}": "function = name() {}",
    "function name() {}": "function name() {}",
    "def name():": "def name():",
    "func name() {}": "func name() {}",
    "() -> {}": "() -> {}",
    "const f = () => {}": "const f = () => {}",
    "function => {}": "function => {}",
    "def f => {}": "def f => {}",
    "Parametr — chaqirganda": "Параметр — при вызове",
    "Argument — e'londa": "Аргумент — при объявлении",
    "Parametr — e'londa, argument — chaqirganda beriladigan qiymat": "Параметр — в объявлении, аргумент — значение, передаваемое при вызове",
    "Funksiyadan qiymat qaytaradi va bajarishni to'xtatadi": "Возвращает значение из функции и останавливает её выполнение",
    "Chop etadi": "Выводит",
    "Funksiyani chaqiradi": "Вызывает функцию",
    "Birinchi parametr": "Первый параметр",
    "Parametrga standart qiymat berish (agar berilmasa)": "Задание значения параметру по умолчанию (если не передано)",
    "Oxirgi parametr": "Последний параметр",
    "Ikkita parametr": "Два параметра",
    "Ob'ekt parametr": "Параметр-объект",
    "Cheksiz miqdordagi argumentlarni array sifatida olish": "Получение неограниченного числа аргументов в виде массива",
    "Funksiya o'chirilishi": "Удаление функции",
    "Funksiya kechiktirilishi": "Отложенный вызов функции",
    "function deklaratsiyalari faylning yuqorisiga ko'tarilishi": "Объявления function поднимаются в начало файла",
    "Birinchi chaqiriladigan funksiya": "Функция, вызываемая первой",
    "Asinxron funksiya": "Асинхронная функция",
    "Boshqa funksiyaga argument sifatida beriladigan funksiya": "Функция, передаваемая другой функции в качестве аргумента",
    "Massivni tartiblaydi": "Сортирует массив",
    "Array oxiriga element qo'shadi": "Добавляет элемент в конец массива",
    "Birinchi elementni qaytaradi": "Возвращает первый элемент",
    "Har elementga funksiya qo'llab yangi array qaytaradi": "Применяет функцию к каждому элементу и возвращает новый массив",
    "Array'ni tartiblaydi": "Сортирует массив",
    "Array'ni bo'sh qiladi": "Опустошает массив",
    "Array'ni filtr qiladi": "Фильтрует массив",
    "Barcha elementlarni o'chiradi": "Удаляет все элементы",
    "Shartga mos elementlardan yangi array qaytaradi": "Возвращает новый массив из элементов, удовлетворяющих условию",
    "Hamma mos elementlarni qaytaradi": "Возвращает все совпадающие элементы",
    "Birinchi mos elementni qaytaradi": "Возвращает первый совпадающий элемент",
    "Indeks qaytaradi": "Возвращает индекс",
    "Elementning massivda bor-yo'qligini boolean qaytaradi": "Возвращает boolean о наличии элемента в массиве",
    "slice yangi array qaytaradi (asl o'zgarmaydi), splice aslini o'zgartiradi": "slice возвращает новый массив (исходный не меняется), splice изменяет исходный",
    "slice o'zgartiradi": "slice изменяет",
    "splice qaytaradi": "splice возвращает",
    "Massivni tartibga solib aslini o'zgartiradi": "Сортирует массив, изменяя исходный",
    "Yangi tartibli array yaratadi": "Создаёт новый отсортированный массив",
    "Massivni filterlaydi": "Фильтрует массив",
    "Saralashni o'chiradi": "Отменяет сортировку",
    "Massivni bitta qiymatga qisqartiradi (yig'indisi, mahsulot va h.k.)": "Сводит массив к одному значению (сумма, произведение и т.д.)",
    "loop(0,n)": "loop(0,n)",
    "for(let i=0; i<n; i++)": "for(let i=0; i<n; i++)",
    "for x in range()": "for x in range()",
    "foreach(n, i)": "foreach(n, i)",
    "Har doim bitta bajariladi": "Всегда выполняется один раз",
    "Shart false bo'lganda": "Когда условие ложно",
    "Soniy bajariladi": "Выполняется определённое число раз",
    "do-while shart tekshirmaydi": "do-while не проверяет условие",
    "do-while kamida bir marta bajariladi": "do-while выполняется минимум один раз",
    "while kamida bir marta bajariladi": "while выполняется минимум один раз",
    "Keyingi iteratsiyaga o'tadi": "Переходит к следующей итерации",
    "Joriy iteratsiyani o'tkazib keyingisiga o'tadi": "Пропускает текущую итерацию и переходит к следующей",
    "Satrlar uchun": "Для строк",
    "Funksiyalar uchun": "Для функций",
    "Array elementlari": "Элементов массива",
    "Ob'ekt kalitlari uchun": "Для ключей объекта",
    "break ishlatmang": "Не используйте break",
    "Shart to'g'ri o'zgarishiga ishonch hosil qiling": "Убедитесь, что условие правильно изменяется",
    "continue ishlatmang": "Не используйте continue",
    "return ishlatmang": "Не используйте return",
    "Switch-case": "Switch-case",
    "arr.count": "arr.count", "arr.len": "arr.len", "arr.length": "arr.length", "arr.size": "arr.size",
    "arr.insert()": "arr.insert()", "arr.append()": "arr.append()", "arr.push()": "arr.push()", "arr.add()": "arr.add()",
    "arr.remove()": "arr.remove()", "arr.delete()": "arr.delete()", "arr.splice()": "arr.splice()", "arr.pop()": "arr.pop()",
    "Iterable elementlari ustidan o'tish": "Перебор элементов итерируемого объекта",
    "Raqamli indeks": "Числовой индекс",
    "Kalit-qiymat juftlari": "Пары ключ-значение",
    "-1": "-1", "1": "1",
    "'undefined'": "'undefined'", "'object'": "'object'", "'array'": "'array'", "'list'": "'list'",
    "undefined": "undefined", "'array'": "'array'", "true": "true", "false": "false",
    "Qiymat indeksini qaytaradi (-1 yo'q bo'lsa)": "Возвращает индекс значения (-1, если не найдено)",
    "Qiymatni o'chiradi": "Удаляет значение",
    "Qiymatni tartiblaydi": "Сортирует значение",
    "Mantiqiy EMAS": "Логическое НЕ",
    "Mantiqiy YOKI": "Логическое ИЛИ",
    "Solishtirish": "Сравнение",
    "Mantiqiy VA — ikkalasi rost bo'lsa rost": "Логическое И — истина, если оба истинны",
    "Mantiqiy YOKI — biri rost bo'lsa rost": "Логическое ИЛИ — истина, если хотя бы один истинен",
    "Mantiqiy VA": "Логическое И",
    "Tenglik": "Равенство",
    "Mantiqiy EMAS — qiymatni teskarisiga aylantiradi": "Логическое НЕ — инвертирует значение",
    "break yo'q bo'lganda keyingi case ham bajarilishi": "Выполнение следующего case при отсутствии break",
    "Rekursiya": "Рекурсия",
    "'hello'": "'hello'",
    "null": "null", "''": "''", "'0'": "'0'",
    "Majburiy operator": "Обязательный оператор",
    "null yoki undefined bo'lsa o'ngdagi qiymatni qaytaradi": "Возвращает значение справа, если слева null или undefined",
    "NULL tekshiruv": "Проверка NULL",
    "Mantiqiy operator": "Логический оператор",
    "Majburiy ulanish": "Обязательное соединение",
    "null/undefined bo'lsa xato bermasdan underfined qaytaradi": "Возвращает undefined без ошибки, если значение null/undefined",
    "Shartga qarab turli ko'rsatma bajarish": "Выполнение разных инструкций в зависимости от условия",
    "Animatsiya qo'shish": "Добавление анимации",
    "O'zgaruvchi yaratish": "Создание переменной",
    "Takrorlash": "Повторение",
    "Oxirgi variant": "Последний вариант",
    "Birinchi shart": "Первое условие",
    "Birinchi shart false bo'lganda tekshiriladigan qo'shimcha shart": "Дополнительное условие, проверяемое, если первое ложно",
    "Har doim bajariladi": "Выполняется всегда",
    "Uch operandli arifmetik operator": "Арифметический оператор с тремя операндами",
    "? : bilan bir qatorli if-else ifodasi": "Однострочное выражение if-else через ? :",
    "Ko'p shartli tekshiruv": "Проверка нескольких условий",
    "O'zgaruvchi turi": "Вид переменной",
    "For sikli": "Цикл for",
    "Ko'p qiymatli shartni boshqarish uchun": "Для управления условием с множеством значений",
    "case blokidan chiqadi": "Выходит из блока case",
    "Sikl boshlaydi": "Запускает цикл",
    "Dasturni to'xtatadi": "Останавливает программу",
    "Hech qaysi case mos kelmasa bajariladigan blok": "Блок, выполняемый, если ни один case не подошёл",
    "Majburiy bo'lim": "Обязательный раздел",
    "Boolean kontekstida rost (truthy) yoki yolg'on (falsy) hisoblanadigan qiymatlar": "Значения, считающиеся истинными (truthy) или ложными (falsy) в булевом контексте",
    "Faqat true/false": "Только true/false",
    "Hisoblash turi": "Вид вычисления",
    "Shart tekshiruvi": "Проверка условия",
    "&& yoki || da birinchi operandga qarab ikkinchisini baholash yoki o'tkazib yuborish": "Вычисление или пропуск второго операнда в && или || в зависимости от первого",
    "Funksiya chaqirish": "Вызов функции",
    "Brauzer va serverlarda ishlaydi, dinamik veb sahifalar yaratish uchun dasturlash tili": "Язык программирования, работающий в браузере и на сервере, для создания динамических веб-страниц",
    "CSS kengaytmasi": "Расширение CSS",
    "HTML turi": "Вид HTML",
    "Ma'lumotlar bazasi tili": "Язык баз данных",
    "let x = 5": "let x = 5", "x: 5": "x: 5", "int x = 5": "int x = 5", "x := 5": "x := 5",
    "Konsolga ma'lumot chiqaradi": "Выводит данные в консоль",
    "Qiymat turini o'zgartiradi": "Меняет тип значения",
    "Qiymat turini qaytaradi": "Возвращает тип значения",
    "null qasddan bo'shatilgan, undefined qiymat berilmagan": "null задан намеренно как пустое значение, undefined — значение не задано",
    "undefined qasddan bo'sh": "undefined задан намеренно как пустое",
    "null berilmagan": "null не задано",
    "let o'zgartirilmaydi": "let нельзя изменять",
    "let o'zgartirilishi mumkin, const o'zgartirish mumkin emas": "let можно изменять, const нельзя",
    "const o'zgartirilishi mumkin": "const можно изменять",
    "Matn qiymati (qo'shtirnoq ichidagi)": "Текстовое значение (в кавычках)",
    "Son": "Число",
    "== qat'iy solishtiradi": "== сравнивает строго",
    "== tur almashtirib solishtiradi, === qat'iy solishtiradi": "== сравнивает с приведением типов, === — строго",
    "=== tur almashtiradi": "=== приводит типы",

    # ---- session 61: HTML/CSS advanced + portfolio projects ----
    "JavaScript portfolio": "JavaScript-портфолио",
    "Server portfolio": "Серверное портфолио",
    "Python portfolio": "Python-портфолио",
    "HTML va CSS bilan yaratilgan shaxsiy ish namoyish sayti": "Сайт-визитка для демонстрации своих работ, созданный на HTML и CSS",
    "Sahifaning birinchi ko'rinadigan katta yuqori bo'limi": "Первый крупный видимый блок вверху страницы",
    "Sidebar": "Боковая панель",
    "Footer": "Подвал",
    "Header": "Шапка",
    "O'zingizning shrift faylini CSS'ga ulash": "Подключение собственного файла шрифта в CSS",
    "CSS animatsiya": "CSS-анимация",
    "CSS grid": "CSS grid",
    "CSS ranglar": "Цвета CSS",
    "Navigatsiya havolasi bosilganda silliq animatsion o'tish": "Плавный анимированный переход при клике по навигационной ссылке",
    "Tez scroll": "Быстрая прокрутка",
    "Scroll qilganda element ko'rinish maydonida qoladi": "Элемент остаётся в области видимости при прокрутке",
    "CSS flex": "CSS flex",
    "Yashirin element": "Скрытый элемент",
    "Elementni qirqib geometrik shakl berish": "Обрезка элемента для придания геометрической формы",
    "Rang o'zgartirish": "Изменение цвета",
    "Elementning orqasidagi kontent ustiga blur yoki boshqa effekt": "Эффект размытия или другой эффект поверх контента за элементом",
    "::-webkit-scrollbar bilan stilizatsiya qilingan scroll paneli": "Панель прокрутки, стилизованная через ::-webkit-scrollbar",
    "Standart scroll": "Стандартная прокрутка",
    "CSS menu": "CSS-меню",
    "JavaScript menu": "JavaScript-меню",
    "Server menu": "Серверное меню",
    "HTML/CSS bilan yaratilgan restoran taomlar menyusi sahifasi": "Страница меню блюд ресторана, созданная на HTML/CSS",
    "Sabit balandlik": "Фиксированная высота",
    "Qator balandligi avtomatik tarkibga moslashadi": "Высота строки автоматически подстраивается под содержимое",
    "CSS rang": "Цвет CSS",
    "Element kenglik-balandlik nisbatini 4:3 ga o'rnatadi": "Задаёт соотношение сторон элемента 4:3",
    "Ovqat kartasi ustida hover effekti (ko'tarilish, soya)": "Эффект наведения на карточку блюда (подъём, тень)",
    "Avtomatik raqamlash uchun CSS maxsus hisoblagich": "Специальный CSS-счётчик для автоматической нумерации",
    "JavaScript hisobi": "Подсчёт на JavaScript",
    "Font yuklash": "Загрузка шрифта",
    "Avval lokal o'rnatilgan fontni tekshirish": "Проверка уже установленного локального шрифта",
    "Forma berish": "Придание формы",
    "Floated element atrofida matnning oqim shaklini belgilash": "Задаёт форму обтекания текста вокруг плавающего элемента",
    "Screen stylesheet": "Стили для экрана",
    "Sahifani chop etish uchun maxsus CSS (@media print)": "Специальный CSS для печати страницы (@media print)",
    "JavaScript blog": "JavaScript-блог",
    "Server blog": "Серверный блог",
    "Python blog": "Python-блог",
    "Moda va uslub haqidagi HTML/CSS sahifasi": "Страница на HTML/CSS о моде и стиле",
    "Flexbox turi": "Вид Flexbox",
    "Grid turi": "Вид grid",
    "column-count bilan matnni ko'p ustunlarga bo'lish": "Разбиение текста на несколько колонок через column-count",
    "Paragrafning birinchi harfini kattalashtirish (::first-letter bilan)": "Увеличение первой буквы абзаца (через ::first-letter)",
    "Element va ostidagi kontent qanday aralashishini belgilash": "Задаёт способ смешивания элемента с содержимым под ним",
    "Fon qoplashtirish": "Наложение фона",
    "Matn yo'nalishi (gorizontal, vertikal)": "Направление текста (горизонтальное, вертикальное)",
    "So'z bo'ginda qo'yiladigan chiziq qoidalari": "Правила расстановки переносов слов по слогам",
    "-webkit-text-stroke bilan matn chegarasi chizish": "Обводка текста через -webkit-text-stroke",
    "Ko'p qatorli matnni n qatorda kesib '...' qo'shish": "Обрезка многострочного текста до n строк с добавлением '...'",
    "Sayohat xizmatlari uchun HTML/CSS reklamasahifasi": "Рекламная страница на HTML/CSS для туристических услуг",
    "JavaScript landing": "JavaScript-лендинг",
    "Server landing": "Серверный лендинг",
    "Python landing": "Python-лендинг",
    "Scroll qilganda fon va mazmun turli tezlikda harakatlanishi": "Фон и контент двигаются с разной скоростью при прокрутке",
    "Scroll bilan harakat": "Движение при прокрутке",
    "Scroll qilganda fon rasm qotib qoladi": "Фоновое изображение остаётся неподвижным при прокрутке",
    "Animatsiya oldin/keyin element holati": "Состояние элемента до/после анимации",
    "Animatsiya rangi": "Цвет анимации",
    "Server karta": "Серверная карточка",
    "JavaScript karta": "JavaScript-карточка",
    "Sayohat joyi haqida ma'lumot ko'rsatuvchi karta komponenti": "Компонент-карточка с информацией о туристическом направлении",
    "CSS karta": "CSS-карточка",
    "Qator bo'shliq": "Промежуток между строками",
    "Grid/flex ustunlari orasidagi bo'shliq": "Промежуток между колонками grid/flex",
    "Rasm fon": "Фон-изображение",
    "Sahifa foni sifatida autoplay muted video": "Автовоспроизводящееся видео без звука в качестве фона страницы",
    "Oddiy tugma": "Обычная кнопка",
    "Scroll qilganda ham ko'rinadigan qolib qoluvchi harakat tugmasi": "Кнопка призыва к действию, остающаяся видимой при прокрутке",
    "Konferensiya yoki tadbir uchun HTML/CSS e'lon sahifasi": "Страница-анонс на HTML/CSS для конференции или мероприятия",
    "CSS timer": "CSS-таймер",
    "Countdown timer stilizatsiyasi (JS bilan birgalikda)": "Стилизация таймера обратного отсчёта (совместно с JS)",
    "Bepul chipta": "Бесплатный билет",
    "Konferensiya chipta narxlari jadval ko'rinishida": "Таблица с ценами на билеты конференции",
    "CSS pricing": "CSS pricing",
    "HTML pricing": "HTML pricing",
    "3D transformatsiya uchun ko'zdan masofani belgilash": "Задаёт расстояние от \"глаза\" для 3D-трансформации",
    "Ma'ruzachilar profili, rasm va bio bilan ko'rsatilgan bo'lim": "Блок с профилями спикеров, фото и биографией",
    "Scroll qilganda elementlarga 'snap' qilish — sectionlar orasida": "Привязка ('snap') к элементам при прокрутке — между секциями",
    "Erkin scroll": "Свободная прокрутка",
    "CSS tur": "Вид CSS",
    "setInterval bilan qolgan vaqtni (kun/soat/daqiqa) yangilab ko'rsatish": "Обновление и отображение оставшегося времени (дни/часы/минуты) через setInterval",
    "Hover bo'lganda karta 3D aylanib orqa tarafini ko'rsatadi": "При наведении карточка поворачивается в 3D и показывает обратную сторону",
    "Birinchi mashq": "Первое упражнение",
    "Kurs bo'yicha barcha bilimlarni birlashtiruvchi yakuniy loyiha": "Финальный проект, объединяющий все знания курса",
    "JavaScript loyiha": "JavaScript-проект",
    "CSS loyiha": "CSS-проект",
    "Semantic HTML + CSS Custom Properties + Responsive + Accessible + Animated": "Semantic HTML + CSS Custom Properties + Responsive + Accessible + Animated",
    "Faqat HTML": "Только HTML",
    "Faqat CSS": "Только CSS",
    "Faqat JS": "Только JS",
    "Oddiy o'zgaruvchi": "Обычная переменная",
    "--color-primary kabi qayta ishlatiladigan dizayn qiymati o'zgaruvchisi": "Переиспользуемая переменная дизайн-значения, например --color-primary",
    "Compositor-only animatsiyalar, akan reflow/repaint CSS": "CSS с анимациями только на композиторе, без reflow/repaint",
    "Ko'p CSS": "Много CSS",
    "Keraksiz": "Не нужно",
    "Loyiha CSS arxitekturasi va o'zgaruvchilarni tavsiflovchi sharh/hujjat": "Комментарии/документация, описывающие архитектуру CSS и переменные проекта",
    "Faqat Chrome": "Только Chrome",
    "HTML test": "HTML-тест",
    "Chrome, Firefox, Safari'da loyihani sinab ko'rish": "Проверка проекта в Chrome, Firefox, Safari",
    "CSS test": "CSS-тест",
    "Statik HTML/CSS saytni GitHub Pages'da bepul joylashtirish": "Бесплатное размещение статического HTML/CSS-сайта на GitHub Pages",
    "JavaScript deploy": "Деплой JavaScript",
    "CSS deploy": "Деплой CSS",
    "Server deploy": "Деплой сервера",
    "HTML uchun": "Для HTML",
    "Ishchilar va mijozlarga qobiliyatni ko'rsatish": "Чтобы показать свои навыки работодателям и клиентам",
    "Qayta ishlatiladigan CSS animatsiya sinflar kutubxonasi (Animate.css kabi)": "Библиотека переиспользуемых CSS-классов анимации (например, Animate.css)",
    "Python kutubxona": "Библиотека Python",
    "Bitta animatsiya": "Одна анимация",
    "Server kutubxona": "Серверная библиотека",
    "@keyframes da animatsiya bosqich nuqtasi (0%, 50%, 100%)": "Опорная точка анимации в @keyframes (0%, 50%, 100%)",
    "Animatsiya davomiyligi": "Длительность анимации",
    "Animatsiya boshlanishdan oldingi kechikish vaqti": "Время задержки перед началом анимации",
    "running yoki paused — animatsiyani boshqarish": "running или paused — управление анимацией",
    "Standart ease": "Стандартный ease",
    "cubic-bezier() bilan o'z tezlashtirish funksiyangizni belgilash": "Задание собственной функции плавности через cubic-bezier()",
    "Bir necha animatsiya bir xil xususiyatni qo'llanganda qanday birlashishi": "Как объединяются несколько анимаций, влияющих на одно свойство",
    "Scroll holatiga bog'liq CSS animatsiyalar (ScrollTimeline)": "CSS-анимации, зависящие от положения прокрутки (ScrollTimeline)",
    "Brauzer rendering mexanizmini paint/layout worklets orqali kengaytirish": "Расширение движка рендеринга браузера через paint/layout worklets",
    "To'liq komponentli SaaS reklamasahifasi HTML/CSS bilan": "Полнофункциональная рекламная страница SaaS на HTML/CSS",
    "Oddiy grid": "Обычная сетка",
    "Turli o'lchamdagi blog joylashuvdan iborat zamonaviy kartalar grid dizayni": "Современный дизайн сетки карточек разного размера",
    "3D perspektiva vanishing point o'rni": "Положение точки схода 3D-перспективы",
    "Rang belgilash": "Задание цвета",
    "Shisha animatsiya": "Стеклянная анимация",
    "backdrop-filter: blur + shaffof fon bilan shisha ko'rinish effekti": "Эффект стекла через backdrop-filter: blur и прозрачный фон",
    "Yumshoq 3D qabariq ko'rinish — açıq fon + yaqin soya juftlari": "Мягкий выпуклый 3D-вид — светлый фон + пары близких теней",
    "Glassmorphism": "Глассморфизм",
    "Focus turi": "Вид фокуса",
    "Ichki elementga focus bo'lsa ota-elementni tanlash": "Выбор родительского элемента, если фокус на дочернем",
    "Checkbox, radio, range kabi forma elementlar asosiy rangini o'rnatish": "Задаёт основной цвет элементов формы, таких как checkbox, radio, range",
    "Rang turi": "Вид цвета",
    "Brauzer UI elementlari uchun light/dark rejimni bildirish": "Указание светлого/тёмного режима для элементов интерфейса браузера",
    "Rang sxemasi": "Цветовая схема",
    "Birinchisidan rivojlangan, ko'proq xususiyatli shaxsiy sayt": "Более развитый, функциональный личный сайт по сравнению с первой версией",
    "cursor: url() yoki CSS bilan o'ziga xos sichqoncha ko'rinishi": "Собственный вид курсора через cursor: url() или CSS",
    "Oddiy cursor": "Обычный курсор",
    "Sahifalar orasida o'tishda CSS animatsiya effekti": "Эффект CSS-анимации при переходе между страницами",
    "Katta animatsiya": "Крупная анимация",
    "Foydalanuvchi harakatiga javob beruvchi kichik, subtil animatsiya": "Небольшая, ненавязчивая анимация в ответ на действие пользователя",
    "CSS custom property'ni animatsiyalanuvchi qiluvchi deklaratsiya": "Декларация, делающая CSS custom property анимируемым",
    "Oddiy xususiyat": "Обычное свойство",
    "JS Canvas API bilan zarralar animatsiyasi": "Анимация частиц через JS Canvas API",
    "CSS particles": "CSS particles",
    "Oddiy fon": "Обычный фон",
    "SVG yoki CSS filter bilan analog don effekti": "Эффект аналоговой зернистости через SVG или CSS filter",
    "offset-path bilan element belgilangan yo'l bo'ylab harakatlanadi": "Элемент движется по заданному пути через offset-path",
    "Chiziqli harakat": "Линейное движение",
    "Texnologiya startapi uchun HTML/CSS zamonaviy sahifasi": "Современная страница на HTML/CSS для технологического стартапа",
    "Statik gradient": "Статичный градиент",
    "@keyframes bilan ranglar silliq almashinadigan fon animatsiyasi": "Анимация фона с плавной сменой цветов через @keyframes",
    "text-shadow/box-shadow bilan neon yonish effekti": "Эффект неонового свечения через text-shadow/box-shadow",
    "steps() funksiyasi bilan matn harfma-harf paydo bo'lishi": "Появление текста побуквенно через функцию steps()",
    "JS effekt": "Эффект на JS",
    "Tarif yoki mahsulot xususiyatlarini taqqoslaydigan jadval": "Таблица, сравнивающая тарифы или характеристики продукта",
    "HTML table": "HTML-таблица",
    "CSS table": "CSS-таблица",
    "Narx jadvali": "Таблица цен",
    "Ichki grid ota-grid chiziqlari bilan moslashishi": "Вложенная сетка выравнивается по линиям родительской сетки",
    "Statik raqam": "Статичное число",
    "JavaScript bilan raqam 0'dan maqsad qiymatigacha animatsiya": "Анимация числа от 0 до целевого значения на JavaScript",
    "JavaScript bilan tema almashish funksiyasi": "Функция смены темы на JavaScript",
    "Notijorat tashkilot uchun HTML/CSS e'lon sahifasi": "Страница-анонс на HTML/CSS для некоммерческой организации",
    "Sahifaga kirishda raqamlar 0'dan maqsad qiymatigacha animatsiya bilan oshadi": "При заходе на страницу числа анимированно увеличиваются от 0 до целевого значения",
    "Xayriya uchun Foydalanuvchini harakat qilishga undovchi tugma": "Кнопка призыва к действию для пожертвования",
    "CSS tugma": "CSS-кнопка",
    "HTML tugma": "HTML-кнопка",
    "WCAG qoidalariga mos matn va fon rang farqi": "Соответствие контраста текста и фона правилам WCAG",
    "Tashkilot jamoasi profili bilan ko'rsatiladigan bo'lim": "Блок с профилями команды организации",
    "CSS bar": "CSS-индикатор",
    "Mablag' yig'ilishi foizini ko'rsatuvchi vizual indikator": "Визуальный индикатор процента собранных средств",
    "Scroll jarayonini animatsiya boshqaruvchisi sifatida ishlatish": "Использование процесса прокрутки как драйвера анимации",
    "CSS region": "CSS region",
    "Dinamik o'zgargan kontent ekran o'quvchiga e'lon qilinadi": "Динамически изменённый контент объявляется программой чтения с экрана",
    "Ijodiy agentlik yoki studio uchun HTML/CSS namoyish sahifasi": "Презентационная страница на HTML/CSS для творческого агентства или студии",
    "Oddiy qoplashtirish": "Обычное наложение",
    "Asosiy rang bilan fon rangini ko'paytirish — quyuqroq effekt": "Умножение основного цвета на цвет фона — эффект затемнения",
    "Tashqarib ketgan kontentni kesib, scrollsiz yashiradi": "Обрезает выходящий за границы контент, скрывая его без прокрутки",
    "Scroll chiqaradi": "Добавляет прокрутку",
    "Belgilangan farzandni bo'lgan ota-elementni tanlash": "Выбор родительского элемента, содержащего указанного потомка",
    "Eski selector": "Устаревший селектор",
    "Viewport emas, konteyner o'lchamiga qarab stil berish": "Стилизация по размеру контейнера, а не viewport",
    "Media query turi": "Вид media query",
    "JS animatsiya": "JS-анимация",
    "Scroll o'lchamiga bog'liq CSS animatsiya (animation-timeline)": "CSS-анимация, зависящая от прокрутки (animation-timeline)",
    "Specificity tartibini boshqarish uchun CSS qatlamlari": "CSS-слои для управления порядком специфичности",
    "CSS media": "CSS media",
    "JavaScript env": "JavaScript env",
    "Safe area inset kabi qurilma muhit qiymatlarini olish": "Получение значений среды устройства, таких как safe area inset",
    "Bitta mahsulot uchun reklamasahifasi HTML/CSS": "Рекламная страница на HTML/CSS для одного продукта",
    "Fon gradient": "Градиентный фон",
    "background-clip:text bilan matn gradientli bo'ladi": "Текст становится градиентным через background-clip: text",
    "Mijozlar fikrlari slayd bo'lib almashinadi": "Отзывы клиентов сменяют друг друга в виде слайдов",
    "CSS list": "CSS-список",
    "Mahsulot afzalliklari va xususiyatlari ro'yxati": "Список преимуществ и особенностей продукта",
    "Mahsulot narxi": "Цена продукта",
    "HTML list": "HTML-список",
    "Muntazam grid": "Обычная сетка",
    "Pinterestga o'xshash har xil balandlikdagi karta joylashuvi": "Расположение карточек разной высоты, как в Pinterest",
    "HTML video": "HTML video",
    "CSS video": "CSS video",
    "Brauzer avtomatik ovoz bilan ijroni bloklaydi — muted shart": "Браузер блокирует автовоспроизведение со звуком — muted обязателен",
    "Ovozli video": "Видео со звуком",
    "Rang qo'shadi": "Добавляет цвет",
    "Rasmni kulrang rangga aylantiradi": "Превращает изображение в оттенки серого",
    "Margin turi": "Вид margin",
    "Sticky header bor bo'lganda anchor link uchun yuqori oraliq": "Верхний отступ для якорной ссылки при наличии липкой шапки",

    # ---- fixups: distinct uz strings caught on first run (plural/case variants) ----
    "O'zgaruvchini o'chiradi": "Удаляет переменную",
    "Barcha ma'lumotni o'chiradi": "Удаляет все данные",
    "Satr": "Строка",
    "Ob'ektni filterlaydi": "Фильтрует объект",
    "Majburiy parametr": "Обязательный параметр",
    "Bitta parametr": "Один параметр",
    "Oxirgi elementni olib tashlaydi": "Удаляет последний элемент",
    "Yangi massiv yaratadi": "Создаёт новый массив",
    "Xato turi": "Вид ошибки",
    "Qiymat qaytaradi": "Возвращает значение",
    "Oxirgi case": "Последний case",
    "Sikl to'xtatish": "Остановка цикла",
    "Qiymatni chiqaradi": "Выводит значение",
    "Matn rangi": "Цвет текста",
    "Oddiy rang": "Обычный цвет",
}


async def main() -> None:
    async with AsyncSessionLocal() as db:
        result = await db.execute(
            select(GameQuestion).where(
                GameQuestion.question_kind == "quiz",
                GameQuestion.session_id.in_(SESSIONS),
                or_(GameQuestion.question_text_ru.is_(None), GameQuestion.question_text_ru == "", GameQuestion.options_ru.is_(None)),
            ).order_by(GameQuestion.id)
        )
        rows = result.scalars().all()
        print(f"Phase 3 remainder: {len(rows)} rows need RU across sessions {SESSIONS}")

        written = 0
        skipped_ids = []
        for row in rows:
            q_ru = QUESTION_MAP.get(row.question_text)
            if q_ru is None:
                print(f"  SKIP id={row.id} session={row.session_id}: no question mapping for {row.question_text!r}")
                skipped_ids.append(row.id)
                continue
            opts_ru = []
            ok = True
            for o in row.options:
                tr = OPTION_MAP.get(o)
                if tr is None:
                    ok = False
                    print(f"  SKIP id={row.id}: missing option mapping for {o!r}")
                opts_ru.append(tr)
            if not ok:
                skipped_ids.append(row.id)
                continue
            row.question_text_ru = q_ru
            row.options_ru = opts_ru
            written += 1

        if written:
            await db.commit()
        else:
            await db.rollback()
        print(f"Phase 3 remainder wrote {written}/{len(rows)} rows.")
        if skipped_ids:
            print(f"Skipped ids: {skipped_ids}")


if __name__ == "__main__":
    asyncio.run(main())
