"""fix user dictionary foreign key

Revision ID: 288d0d8f2add
Revises: 4a74ca38d855
Create Date: 2026-05-21 14:17:29.731610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288d0d8f2add'
down_revision: Union[str, None] = '4a74ca38d855'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
