"""remove role from students

Revision ID: 35175fbb9150
Revises: 61e0f7a491d3
Create Date: 2026-03-10 15:55:50.836588

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '35175fbb9150'
down_revision: Union[str, None] = '61e0f7a491d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('role', postgresql.ENUM('student', 'instructor', 'admin', name='userrole'), server_default=sa.text("'student'::userrole"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
