"""add user dictionary table

Revision ID: 355d2ccdf844
Revises: e9ffa98bf2c0
Create Date: 2026-05-21 15:04:03.113069

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '355d2ccdf844'
down_revision: Union[str, None] = 'e9ffa98bf2c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
