"""add lesson submission fields

Revision ID: 36854854feda
Revises: 0b906f51884f
Create Date: 2026-03-23 16:03:27.539724

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '36854854feda'
down_revision: Union[str, None] = '0b906f51884f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('submissions', sa.Column('lesson_id', sa.Integer(), nullable=True))
    op.add_column('submissions', sa.Column('github_url', sa.String(length=255), nullable=True))
    op.add_column('submissions', sa.Column('live_demo_url', sa.String(length=255), nullable=True))
    op.add_column('submissions', sa.Column('description', sa.Text(), nullable=True))
    op.alter_column('submissions', 'submitted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('submissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.alter_column('submissions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.create_foreign_key(None, 'submissions', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.alter_column('submissions', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('submissions', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.alter_column('submissions', 'submitted_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_column('submissions', 'description')
    op.drop_column('submissions', 'live_demo_url')
    op.drop_column('submissions', 'github_url')
    op.drop_column('submissions', 'lesson_id')
    # ### end Alembic commands ###
