"""convert_lesson_content_to_text

Revision ID: 55b0b520983a
Revises: f3cbc27d9853
Create Date: 2026-05-08 19:10:03.451485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55b0b520983a'
down_revision: Union[str, None] = 'f3cbc27d9853'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
