"""fix_student_ranking_relationship

Revision ID: 58111f9dab54
Revises: f97620dc4f54
Create Date: 2026-03-19 15:03:55.319394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58111f9dab54'
down_revision: Union[str, None] = 'f97620dc4f54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('rankings_student_id_fkey', 'rankings', type_='foreignkey')
    op.create_foreign_key(None, 'rankings', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rankings', type_='foreignkey')
    op.create_foreign_key('rankings_student_id_fkey', 'rankings', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
