"""update_course_enrollment_and_instructor

Revision ID: 591f848e2cf4
Revises: 395c50a77b25
Create Date: 2026-03-19 13:30:49.881915

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '591f848e2cf4'
down_revision: Union[str, None] = '395c50a77b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
