"""initial_migration

Revision ID: 62c6a4066a74
Revises: 
Create Date: 2026-05-01 19:54:08.500822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62c6a4066a74'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.alter_column('groups', 'price',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('lessons', sa.Column('chapter', sa.String(length=200), nullable=True))
    op.add_column('lessons', sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False))
    op.drop_constraint('student_degrees_degree_id_fkey', 'student_degrees', type_='foreignkey')
    op.drop_constraint('student_degrees_student_id_fkey', 'student_degrees', type_='foreignkey')
    op.create_foreign_key(None, 'student_degrees', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_degrees', 'degrees', ['degree_id'], ['id'], ondelete='CASCADE')
    op.alter_column('students', 'balance',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.drop_constraint('submissions_project_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_student_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_lesson_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_lesson_id_fkey', 'submissions', 'lessons', ['lesson_id'], ['id'])
    op.create_foreign_key('submissions_student_id_fkey', 'submissions', 'students', ['student_id'], ['id'])
    op.create_foreign_key('submissions_project_id_fkey', 'submissions', 'projects', ['project_id'], ['id'])
    op.alter_column('students', 'balance',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_constraint(None, 'student_degrees', type_='foreignkey')
    op.drop_constraint(None, 'student_degrees', type_='foreignkey')
    op.create_foreign_key('student_degrees_student_id_fkey', 'student_degrees', 'students', ['student_id'], ['id'])
    op.create_foreign_key('student_degrees_degree_id_fkey', 'student_degrees', 'degrees', ['degree_id'], ['id'])
    op.drop_column('lessons', 'is_published')
    op.drop_column('lessons', 'chapter')
    op.alter_column('groups', 'price',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('courses', 'is_published')
    # ### end Alembic commands ###
