"""added achievements and certificates

Revision ID: 7082b573ac47
Revises: 3484716728ea
Create Date: 2026-04-07 21:28:09.820528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7082b573ac47'
down_revision: Union[str, None] = '3484716728ea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_student_achievement', 'student_achievements', ['student_id', 'achievement_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_student_achievement', 'student_achievements', type_='unique')
    # ### end Alembic commands ###
