"""rename course image fields to image_url

Revision ID: 8be7555c7a58
Revises: f1ab21cbf663
Create Date: 2026-03-18 21:27:43.842583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be7555c7a58'
down_revision: Union[str, None] = 'f1ab21cbf663'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_url', sa.String(length=500), nullable=True))
    op.drop_column('courses', 'img_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('img_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('courses', 'image_url')
    # ### end Alembic commands ###
