"""final_setup_course_and_enrollments

Revision ID: 9892969a07ca
Revises: f5c1741ef11b
Create Date: 2026-03-19 13:54:39.944374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9892969a07ca'
down_revision: Union[str, None] = 'f5c1741ef11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
