"""rename course image fields to img_url

Revision ID: a3c74d59cfe9
Revises: 5ca00e4d656b
Create Date: 2026-03-18 20:14:01.110775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3c74d59cfe9'
down_revision: Union[str, None] = '5ca00e4d656b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('img_url', sa.String(length=500), nullable=True))
    op.drop_column('courses', 'syllabus_url')
    op.drop_column('courses', 'video_intro_url')
    op.drop_column('courses', 'cover_image_url')
    op.drop_column('courses', 'thumbnail_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('cover_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('video_intro_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('courses', sa.Column('syllabus_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('courses', 'img_url')
    # ### end Alembic commands ###
