"""add_prerequisite_course_id_to_courses

Revision ID: ac453c212680
Revises: cb31d6df8d5e
Create Date: 2026-04-16 20:05:18.107605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac453c212680'
down_revision: Union[str, None] = 'cb31d6df8d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('prerequisite_course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'courses', 'courses', ['prerequisite_course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_column('courses', 'prerequisite_course_id')
    # ### end Alembic commands ###
