"""add user dictionary table

Revision ID: ae7fa14db1a3
Revises: 78e9c4a0b40b
Create Date: 2026-05-21 16:03:19.833493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae7fa14db1a3'
down_revision: Union[str, None] = '78e9c4a0b40b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
