"""add_sections_json_to_lessons

Revision ID: b12419fc579a
Revises: 49b0f8df8fb9
Create Date: 2026-05-12 15:33:36.639337

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b12419fc579a'
down_revision: Union[str, None] = '49b0f8df8fb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('student_degrees_student_id_fkey', 'student_degrees', type_='foreignkey')
    op.drop_constraint('student_degrees_degree_id_fkey', 'student_degrees', type_='foreignkey')
    op.create_foreign_key(None, 'student_degrees', 'degrees', ['degree_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_degrees', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('submissions_lesson_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_project_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_student_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_student_id_fkey', 'submissions', 'students', ['student_id'], ['id'])
    op.create_foreign_key('submissions_project_id_fkey', 'submissions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key('submissions_lesson_id_fkey', 'submissions', 'lessons', ['lesson_id'], ['id'])
    op.drop_constraint(None, 'student_degrees', type_='foreignkey')
    op.drop_constraint(None, 'student_degrees', type_='foreignkey')
    op.create_foreign_key('student_degrees_degree_id_fkey', 'student_degrees', 'degrees', ['degree_id'], ['id'])
    op.create_foreign_key('student_degrees_student_id_fkey', 'student_degrees', 'students', ['student_id'], ['id'])
    # ### end Alembic commands ###
