"""add assigned_by to projects

Revision ID: b6831d2ea473
Revises: f292edbf2ef0
Create Date: 2026-03-18 20:54:41.793997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6831d2ea473'
down_revision: Union[str, None] = 'f292edbf2ef0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('assigned_by', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('is_assigned', sa.Boolean(), nullable=False, server_default='false'))
    op.create_foreign_key(None, 'projects', 'students', ['assigned_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'is_assigned')
    op.drop_column('projects', 'assigned_by')
    # ### end Alembic commands ###
