"""rename course image fields to img_url

Revision ID: d64fbfec2cd1
Revises: fcbe9f44dd7a
Create Date: 2026-03-18 20:29:24.060158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd64fbfec2cd1'
down_revision: Union[str, None] = 'fcbe9f44dd7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
