"""create user dictionary table

Revision ID: e9ffa98bf2c0
Revises: 288d0d8f2add
Create Date: 2026-05-21 14:52:45.455660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9ffa98bf2c0'
down_revision: Union[str, None] = '288d0d8f2add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
