"""add sections_json to lesson

Revision ID: f3cbc27d9853
Revises: 62c6a4066a74
Create Date: 2026-05-06 22:36:46.312781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f3cbc27d9853'
down_revision: Union[str, None] = '62c6a4066a74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('sections_json', sa.Text(), nullable=True))
    op.drop_column('lessons', 'content_blocks_order')
    op.drop_column('lessons', 'content_blocks')
    op.drop_constraint('student_degrees_student_id_fkey', 'student_degrees', type_='foreignkey')
    op.drop_constraint('student_degrees_degree_id_fkey', 'student_degrees', type_='foreignkey')
    op.create_foreign_key(None, 'student_degrees', 'degrees', ['degree_id'], ['id'])
    op.create_foreign_key(None, 'student_degrees', 'students', ['student_id'], ['id'])
    op.drop_constraint('submissions_project_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_student_id_fkey', 'submissions', type_='foreignkey')
    op.drop_constraint('submissions_lesson_id_fkey', 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'submissions', 'lessons', ['lesson_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key('submissions_lesson_id_fkey', 'submissions', 'lessons', ['lesson_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('submissions_student_id_fkey', 'submissions', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('submissions_project_id_fkey', 'submissions', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'student_degrees', type_='foreignkey')
    op.drop_constraint(None, 'student_degrees', type_='foreignkey')
    op.create_foreign_key('student_degrees_degree_id_fkey', 'student_degrees', 'degrees', ['degree_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('student_degrees_student_id_fkey', 'student_degrees', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.add_column('lessons', sa.Column('content_blocks', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('lessons', sa.Column('content_blocks_order', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text('\'["text", "code", "video", "image", "file"]\'::json'), autoincrement=False, nullable=True))
    op.drop_column('lessons', 'sections_json')
    # ### end Alembic commands ###
