"""rename course image fields to img_url

Revision ID: fcbe9f44dd7a
Revises: 46b0aa5a5075
Create Date: 2026-03-18 20:24:00.679435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcbe9f44dd7a'
down_revision: Union[str, None] = '46b0aa5a5075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
