"""add_groups_and_student_relation

Revision ID: 098fc3fa77cc
Revises: 13c8ba369748
Create Date: 2026-03-19 16:11:15.504433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '098fc3fa77cc'
down_revision: Union[str, None] = '13c8ba369748'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
