"""remove cover_image_url from courses

Revision ID: 0b906f51884f
Revises: eda6c9b6980c
Create Date: 2026-03-23 15:46:43.464600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b906f51884f'
down_revision: Union[str, None] = 'eda6c9b6980c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
