"""add points_reward to lessons

Revision ID: 3210e760c2fb
Revises: f59708055f29
Create Date: 2026-04-05 13:02:03.836958

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3210e760c2fb'
down_revision: Union[str, None] = 'f59708055f29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_completions', 'points_reward')
    op.add_column('lessons', sa.Column('points_reward', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'points_reward')
    op.add_column('lesson_completions', sa.Column('points_reward', sa.INTEGER(), server_default=sa.text('10'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
