"""rename course image fields to img_url

Revision ID: 46b0aa5a5075
Revises: a3c74d59cfe9
Create Date: 2026-03-18 20:22:06.110809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '46b0aa5a5075'
down_revision: Union[str, None] = 'a3c74d59cfe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
