"""Fix student_achievements cascade and timezone

Revision ID: 5e7cc27693ab
Revises: d9826b8a2bbd
Create Date: 2026-03-21 23:48:07.322669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5e7cc27693ab'
down_revision: Union[str, None] = 'd9826b8a2bbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('student_achievements', 'earned_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_constraint('student_achievements_student_id_fkey', 'student_achievements', type_='foreignkey')
    op.drop_constraint('student_achievements_achievement_id_fkey', 'student_achievements', type_='foreignkey')
    op.create_foreign_key(None, 'student_achievements', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'student_achievements', 'achievements', ['achievement_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.create_foreign_key('student_achievements_achievement_id_fkey', 'student_achievements', 'achievements', ['achievement_id'], ['id'])
    op.create_foreign_key('student_achievements_student_id_fkey', 'student_achievements', 'students', ['student_id'], ['id'])
    op.alter_column('student_achievements', 'earned_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    # ### end Alembic commands ###
