"""fix rankings defaults

Revision ID: 92af3b3d1a48
Revises: e22ab3e4a55b
Create Date: 2026-03-22 19:23:59.231790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92af3b3d1a48'
down_revision: Union[str, None] = 'e22ab3e4a55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
