"""add course_certificates table

Revision ID: a8a0b8cbe7c9
Revises: a2c74f78e883
Create Date: 2026-04-05 12:06:15.842866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a0b8cbe7c9'
down_revision: Union[str, None] = 'a2c74f78e883'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
