"""Add task fields to lessons

Revision ID: afc409d47749
Revises: 8a13d9279eab
Create Date: 2026-03-15 14:33:41.553740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'afc409d47749'
down_revision: Union[str, None] = '8a13d9279eab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lessons', sa.Column('task_title', sa.String(length=200), nullable=True))
    op.add_column('lessons', sa.Column('task_description', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('task_requirements', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('task_technologies', sa.Text(), nullable=True))
    op.add_column('lessons', sa.Column('task_deadline_days', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lessons', 'task_deadline_days')
    op.drop_column('lessons', 'task_technologies')
    op.drop_column('lessons', 'task_requirements')
    op.drop_column('lessons', 'task_description')
    op.drop_column('lessons', 'task_title')
    # ### end Alembic commands ###
