"""add points_reward to lessons

Revision ID: b5855880db8a
Revises: a8a0b8cbe7c9
Create Date: 2026-04-05 12:35:37.704071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5855880db8a'
down_revision: Union[str, None] = 'a8a0b8cbe7c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson_completions', sa.Column('points_reward', sa.Integer(), server_default='10', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson_completions', 'points_reward')
    # ### end Alembic commands ###
