"""remove assigned_by to projects

Revision ID: bdbb1284aaf0
Revises: b6831d2ea473
Create Date: 2026-03-18 21:02:39.602107

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdbb1284aaf0'
down_revision: Union[str, None] = 'b6831d2ea473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('video_intro_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('syllabus_url', sa.String(length=500), nullable=True))
    op.drop_column('courses', 'img_url')
    op.drop_constraint('projects_assigned_by_fkey', 'projects', type_='foreignkey')
    op.drop_column('projects', 'assigned_by')
    op.drop_column('projects', 'is_assigned')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('is_assigned', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('projects', sa.Column('assigned_by', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('projects_assigned_by_fkey', 'projects', 'students', ['assigned_by'], ['id'], ondelete='SET NULL')
    op.add_column('courses', sa.Column('img_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_column('courses', 'syllabus_url')
    op.drop_column('courses', 'video_intro_url')
    op.drop_column('courses', 'thumbnail_url')
    op.drop_column('courses', 'cover_image_url')
    # ### end Alembic commands ###
