"""add_course_id_to_achievements

Revision ID: cb31d6df8d5e
Revises: 7a7f73a01694
Create Date: 2026-04-14 16:42:18.553156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb31d6df8d5e'
down_revision: Union[str, None] = '7a7f73a01694'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student_achievements', sa.Column('course_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'student_achievements', 'courses', ['course_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student_achievements', type_='foreignkey')
    op.drop_column('student_achievements', 'course_id')
    # ### end Alembic commands ###
