"""add_team_projects_tables

New feature: Team Projects (AI-planned collaborative projects), Phase 2.
Adds team_projects, team_project_teams, team_project_members,
team_project_tasks, team_project_peer_ratings, and team_project_events —
see app/models/team_project.py for the full status-machine/relationship
docs. Purely additive, no existing table touched.

Revision ID: d13ba7f94af9
Revises: dc9484690959
Create Date: 2026-09-11 22:23:31.486810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd13ba7f94af9'
down_revision: Union[str, None] = 'dc9484690959'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team_projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('planning', 'pending_approval', 'active', 'integrating', 'submitted', 'reviewed', 'cancelled', name='teamprojectstatus'), nullable=False),
    sa.Column('team_size', sa.Integer(), nullable=False),
    sa.Column('deadline_days', sa.Integer(), nullable=False),
    sa.Column('auto_activate_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['students.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_project_teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('lead_student_id', sa.Integer(), nullable=True),
    sa.Column('final_project_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('forming', 'working', 'integrating', 'submitted', 'reviewed', name='teamstatus'), nullable=False),
    sa.Column('integration_unlocked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_plan_json', sa.Text(), nullable=True),
    sa.Column('plan_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generation_attempts', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['final_project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lead_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_project_id'], ['team_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_project_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_project_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('actor_student_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team_project_teams.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_project_id'], ['team_projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('team_project_members',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('member', 'lead', name='teamrole'), nullable=False),
    sa.Column('level_at_assignment', sa.String(length=20), nullable=False),
    sa.Column('skill_summary_at_assignment', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team_project_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'student_id', name='uq_team_project_member')
    )
    op.create_table('team_project_peer_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('rater_student_id', sa.Integer(), nullable=False),
    sa.Column('rated_student_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['rated_student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rater_student_id'], ['students.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['team_id'], ['team_project_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'rater_student_id', 'rated_student_id', name='uq_team_project_peer_rating')
    )
    op.create_table('team_project_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('assigned_student_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('title_ru', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('required_level', sa.String(length=20), nullable=False),
    sa.Column('interface_contract_json', sa.Text(), nullable=False),
    sa.Column('acceptance_criteria_json', sa.Text(), nullable=False),
    sa.Column('depends_on_json', sa.Text(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('assigned', 'submitted', 'changes_requested', 'approved', 'blocked', 'reassigned', name='taskstatus'), nullable=False),
    sa.Column('submission_url', sa.String(length=255), nullable=True),
    sa.Column('submission_files', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ai_score', sa.Integer(), nullable=True),
    sa.Column('ai_feedback_json', sa.Text(), nullable=True),
    sa.Column('lead_comment', sa.Text(), nullable=True),
    sa.Column('points_awarded', sa.Integer(), nullable=False),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_student_id'], ['students.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['team_id'], ['team_project_teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
    # NOTE: autogenerate also detected quizzes.grade_min/grade_max/course_id
    # + a course_id FK as "added" here — deliberately NOT included. Those
    # columns already exist on production (added by a concurrent feature
    # push, `acb23b2`, that never shipped its own migration — alembic isn't
    # wired into this repo's deploy pipeline, see PROJECT_KNOWLEDGE.md
    # §3.1), so an ADD COLUMN for them here would fail outright against the
    # live DB ("column already exists"). This migration is scoped to
    # exactly the team_projects tables it was written for.


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('team_project_tasks')
    op.drop_table('team_project_peer_ratings')
    op.drop_table('team_project_members')
    op.drop_table('team_project_events')
    op.drop_table('team_project_teams')
    op.drop_table('team_projects')
    # ### end Alembic commands ###
    # drop_table() does not drop the Postgres ENUM types it implicitly
    # created (autogenerate only emits CREATE TYPE, never DROP TYPE) — same
    # gotcha as badbe46c1225's baseline migration.
    bind = op.get_bind()
    for enum_name in ('teamprojectstatus', 'teamstatus', 'teamrole', 'taskstatus'):
        sa.Enum(name=enum_name).drop(bind, checkfirst=True)
