"""drop_dead_exercise_ru_columns

Exercise.title_ru/description_ru/hint_ru/explanation_ru/expected_answer_ru
were never read by any serving code — live RU translation for exercises
goes exclusively through translation_cache (see
app/api/v1/endpoints/exercises.py::_translate_exercise_dto). Verified
before this migration: every one of the 411 exercises with legacy data in
these columns already had an equivalent live translation_cache entry (0
gap), so nothing is lost. A pre-drop backup of the non-null rows lives in
the exercises_dead_ru_columns_backup_20260911 table on the production DB.

Revision ID: dc9484690959
Revises: badbe46c1225
Create Date: 2026-09-11 19:36:37.769303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc9484690959'
down_revision: Union[str, None] = 'badbe46c1225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'title_ru')
    op.drop_column('exercises', 'expected_answer_ru')
    op.drop_column('exercises', 'explanation_ru')
    op.drop_column('exercises', 'hint_ru')
    op.drop_column('exercises', 'description_ru')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('description_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('hint_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('explanation_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('expected_answer_ru', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('exercises', sa.Column('title_ru', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
