"""Simplify course relationships

Revision ID: e22ab3e4a55b
Revises: 89f8f23eef5d
Create Date: 2026-03-22 15:24:13.050806

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e22ab3e4a55b'
down_revision: Union[str, None] = '89f8f23eef5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_courses',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'course_id')
    )
    op.drop_table('course_enrollments')
    op.add_column('courses', sa.Column('cover_image_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('thumbnail_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('video_intro_url', sa.String(length=500), nullable=True))
    op.add_column('courses', sa.Column('syllabus_url', sa.String(length=500), nullable=True))
    op.drop_constraint('courses_instructor_id_fkey', 'courses', type_='foreignkey')
    op.create_foreign_key(None, 'courses', 'students', ['instructor_id'], ['id'], ondelete='CASCADE')
    op.drop_column('courses', 'image_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.create_foreign_key('courses_instructor_id_fkey', 'courses', 'students', ['instructor_id'], ['id'])
    op.drop_column('courses', 'syllabus_url')
    op.drop_column('courses', 'video_intro_url')
    op.drop_column('courses', 'thumbnail_url')
    op.drop_column('courses', 'cover_image_url')
    op.create_table('course_enrollments',
    sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('progress_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('is_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enrolled_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('completed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='course_enrollments_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], name='course_enrollments_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('student_id', 'course_id', name='course_enrollments_pkey')
    )
    op.drop_table('student_courses')
    # ### end Alembic commands ###
