"""Add image_url field to courses table

Revision ID: eda6c9b6980c
Revises: 92af3b3d1a48
Create Date: 2026-03-23 14:31:32.067801

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eda6c9b6980c'
down_revision: Union[str, None] = '92af3b3d1a48'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('courses', 'image_url')
    # ### end Alembic commands ###
