"""rename course image fields to image_url

Revision ID: f292edbf2ef0
Revises: d64fbfec2cd1
Create Date: 2026-03-18 20:30:24.925487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f292edbf2ef0'
down_revision: Union[str, None] = 'd64fbfec2cd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
