"""create_course_enrollments_table

Revision ID: f5c1741ef11b
Revises: b62001aee2a6
Create Date: 2026-03-19 13:52:35.894502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5c1741ef11b'
down_revision: Union[str, None] = 'b62001aee2a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lessons')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lessons',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('course_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('order', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('text_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code_content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('code_language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('file_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('task_title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('task_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_requirements', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_technologies', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('task_deadline_days', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='lessons_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name='lessons_project_id_fkey', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='lessons_pkey')
    )
    # ### end Alembic commands ###
