from app.models.user import Student
from app.models.project import Project
from app.models.submission import Submission
from app.models.ranking import Ranking
from app.models.student_degree import StudentDegree
from app.models.achievement import Achievement
from app.models.student_achievement import StudentAchievement
from app.models.course import Course
from app.models.degree import Degree
from app.models.lesson import Lesson
from app.models.group import Group